### ISSUE TITLE
Check DEC sign

### ISSUE THREAD

**Issue by karl-mannheim** [nasa-gcn/gcn.nasa.gov#1102]
The sign of the DEC for the IC event and the associated Fermi objects disagree...  Please, check this.
Karl

**Comment by jracusin** [comment]
@karl-mannheim Sorry, I missed this.  Which event are you referring to?  Is this in notices or circulars?

**Comment by blaufuss** [comment]
@karl-mannheim happy to take a closer look, if you could please provide a bit more details on what you're seeing, it will
help us check into this.  thx.

**Comment by lpsinger** [comment]
Closing this due to lack of feedback.
