### ISSUE TITLE
Tar file for Circulars archive

### ISSUE THREAD

**Issue by Vidushi-GitHub** [nasa-gcn/gcn.nasa.gov#1109]
Alike classic GCN circulars, tar file of all GCN circulars would be useful feature.
We can add more option for this download option, e.x. date range?

**Comment by Vidushi-GitHub** [comment]
Ohh, then what about grouping as free price cap? It may be useful for follow-up teams.

**Comment by lpsinger** [comment]
I don't understand your last comment.

**Comment by Vidushi-GitHub** [comment]
@Courey we can close this, if tar GCN Circulars task is completed.

**Comment by lpsinger** [comment]
No, it's not completed. See #1182.
