### ISSUE TITLE
Configure GITHUB_API_TOKEN for schema browser

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#1187]
We need to set `GITHUB_API_TOKEN` for the schema browser.

- [x] Document the kind of token: fine grained or classic, and required permissions or scopes. I think that if we use a classic token with no scope, we can have it be valid indefinitely and have read-only access by setting no scopes.
- [x] Create three different tokens, one for each deployment stage.
- [x] Install the tokens using the [arc env cli](https://arc.codes/docs/en/reference/cli/env).
- [x] Do a manual deployment of the web site (npm run deploy) for each stage.

**Comment by dakota002** [comment]
For the 1st point: https://github.com/nasa-gcn/gcn.nasa.gov/pull/1188
