### ISSUE TITLE
Remove "Submitted By" from circulars archive

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#1202]
useful for our own internal tracking, not needed for public archive

**Comment by lpsinger** [comment]
Is there any reason _not_ to make this information public?

My model for this feature had been GitHub Issues, which as far as I recall do annotate visibly which comments were submitted by email.

**Comment by jracusin** [comment]
I feel like it's a little weird to display how people submit them, as it felt like publicly shaming people for using the legacy email, but maybe that'll encourage them to use the new system.  I suppose there's no harm.  Okay, I'll close this.  Also, I'm happy to see that many users are using the web form.
