### ISSUE TITLE
Contact form is broken

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#1203]
![Screen Shot 2023-08-08 at 4 14 00 PM](https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/2d9896ed-6f88-4c92-b60e-d08460515250)

**Comment by lpsinger** [comment]
Did #1204 fix this?

**Comment by lpsinger** [comment]
Fixed by #1204.
