### ISSUE TITLE
gcn.notices.icecube.lvk_nu_track_search example JSON package has bad/missing keys

### ISSUE THREAD

**Issue by swyatt7** [nasa-gcn/gcn.nasa.gov#1230]
I've set up a gcn-kafka listener to pickup detected coincident icecube neutrino events to LVK alerts for the [Gravitational Wave Treasure Map](https://treasuremap.space). I used the [example json package](https://raw.githubusercontent.com/nasa-gcn/gcn-schema/main/gcn/notices/icecube/LvkNuTrackSearch.example.json) and have noticed inconsistencies in the actual alerts being sent over this kafka stream that caused some inability to associate events to LVK alerts.

- The `ref_ID` keyword in the example is actually `ref_id` in the alerts, which caused us to actually never associate the alerts to the events.

- The format of the `ref_id` was never documented. We just assumed it would be the graceid for the event like it is in the example, but the actual alert `ref_id` is in the form of `graceid_iter_alerttype` like `S230814r-2-Preliminary`. 

- There is no `reference` keyword in the package that links to the gcn.notices.LVK.alert id. 

- The link to the package [$schema](https://gcn.nasa.gov/schema/gcn/notices/icecube/LvkNuTrackSearch.schema.json) returns 404

- In the `coincident_events` list, the spatial keywords are behind a `"localization"` dictionary, that isn't in the example.

We will update our listener to adapt to what is being sent over the kafka stream, yet request the example.json package also be updated to reflect what is being sent out over kafka. 

Best,

-SW

**Comment by blaufuss** [comment]
@swyatt7 thanks for the deep checking and apologies for the slow reply.  

https://github.com/nasa-gcn/gcn-schema/pull/106

Corrects the example.  Additionally, there are a few tweaks we need to make the example match the schema.  These are not yet in production, but staged and ready to go.  Once we get the PR accepted in gcn-schema and new example published, we will change our production alert sender and close/update this issue when live.  

Just to be clear:  example in PR matches what WILL be coming after new version is live.

Thanks again, welcome any additional feedback

**Comment by blaufuss** [comment]
@swyatt7 this has been merged and tagged as a new stable version of the gcn-schema.

Our sender is being updated now and should be online in the next ~10 minutes to produce gcn notices that match the schema and example published there:

https://raw.githubusercontent.com/nasa-gcn/gcn-schema/v2.0.0/gcn/notices/icecube/LvkNuTrackSearch.example.json
https://raw.githubusercontent.com/nasa-gcn/gcn-schema/v2.0.0/gcn/notices/icecube/LvkNuTrackSearch.schema.json

Please get in touch or send us an issue if you find any problems.

Best
Erik

**Comment by blaufuss** [comment]
@lpsinger I do not have permissions to close this ticket assigned to me.
