### ISSUE TITLE
http://dev.gcn.nasa.gov/docs/schema returns 404 error

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#1450]

**Comment by dakota002** [comment]
This is correct, all links should point to https://dev.gcn.nasa.gov/docs/schema/{version}/gcn

**Comment by lpsinger** [comment]
Right. I'd like /docs/schema to redirect to /docs/schema/stable, and /docs/schema/$version to redirect to /docs/schema/$version/gcn.

**Comment by lpsinger** [comment]
Fixed by #1483.
