### ISSUE TITLE
QuickStart widget - documentation on how to use code

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#151]
We need documentation and examples for what to do with the code generated by the QuickStart widget.

**Comment by lpsinger** [comment]
This has two parts:

1. [ ] Add installation instructions to Quick Start output step.
2. [ ] Reference Quick Start in client section of documentation.

**Comment by jracusin** [comment]
This is a good start, but we need more than this.  We need to show examples of copying this into a .py file or into a python notebook, how to parse the alerts, how to save them.  Can we retrieve historical alerts?  What happens if you disconnect and want to read back the ones you've missed?  Imagine someone is not an expert python user.  This could be a tab on documentation.  Example notebooks would be a great way to show these tasks.

**Comment by jracusin** [comment]
Remaining task is to provide code samples of:
- how to save into a file
- parsing text alerts into dict
- parsing VOEvent alerts into dict
- add examples from gcn-kafka-python to documentation
