### ISSUE TITLE
New Circular page has overlapping text in InputGroups

### ISSUE THREAD

**Issue by dakota002** [nasa-gcn/gcn.nasa.gov#1522]
Likely caused by the introduction of the `position:absolute` and other style changes in https://github.com/uswds/uswds/pull/5063, file 
 `packages/usa-input-prefix-suffix/src/styles/_usa-input-prefix-suffix.scss`

It looks like the assumed use is that the text in `InputPrefix` should be limited to ~3 characters, or an Icon 

![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/e8e89018-6d14-42e9-88aa-a89d0464be35)

**Comment by lpsinger** [comment]
Crap. Can you make a PR to revert the update?
