### ISSUE TITLE
Can't turn off Notices

### ISSUE THREAD

**Issue by mmfausnaugh** [nasa-gcn/gcn.nasa.gov#1541]
While experimenting with the new GCN, I tried turning on Fermi notices.  When trying to turn these off, I can't save the setting ('Save' button is greyed out). It's a specific corner case where I want to deactivate *all* notices.

For now, I turned off the full set of Fermi notices and am just subscribed to GBM alert notices.

I heard about the latest GCN at the Tucson MMA conference---thanks for setting this up, it looks like a great system!

**Comment by lpsinger** [comment]
That's correct. You can't create an email notification with no notice types selected, and if you edit an email notification then you can't save it with no notice types selected either. Just delete the email notification setting entirely to disable it.

Does that address your issue?

**Comment by lpsinger** [comment]
Would it be more clear if we also had a Delete button on the Edit page?

**Comment by mmfausnaugh** [comment]
For me, yes;

**Comment by lpsinger** [comment]
@dakota002, would you please take a look at this?

**Comment by dakota002** [comment]
Re-opening this to link the PR to
