### ISSUE TITLE
Producer documentation suggestion

### ISSUE THREAD

**Issue by joshuarwood** [nasa-gcn/gcn.nasa.gov#1545]
I tested the suggested producer configuration provided at https://gcn.nasa.gov/docs/notices/producers to see how it behaved when a network connection was unavailable. This was done by setting a bogus domain name. Here is the code I used:
```
import json
from gcn_kafka import Producer

producer = Producer(client_id='fill me in', client_secret='fill me in', domain='bogus.gcn.nasa.gov')
topic = 'gcn.notices.mission'
# JSON data converted to byte string format
data = json.dumps({
    '$schema': 'https://gcn.nasa.gov/schema/main/gcn/notices/mission/SchemaName.schema.json',
    'key': 'value'
}).encode()
producer.produce(topic, data)
```
The response was an immediate error message and a failure to send the message: 
```
%4|1697127599.555|TERMINATE|rdkafka#producer-1| [thrd:app]: Producer terminating with 1 message (106 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```
I think this behavior should be avoided because it will result in lost messages even for small connection drops, as have been seen for GW alerts through GCN Kafka during O4.

The error message recommends the addition of `flush()` to the current Producer example to allow a wait period before giving up on the message send. I did this by appending `producer.flush()` to the code above but it also results in undesirable behavior. In this case, the example waited for the message to send but ended without throwing an error after the default wait period (5 min). I had to set an explicit timeout with `producer.flush(timeout=300)` in order to both wait for the connection and throw an error if the message could not be sent after the wait period.

I'm open to other suggestions if you have them but otherwise I would recommend adding something like `producer.flush(timeout=300)` to the producer example.

Versioning details:
* Mac OS Ventura 13.6
* Python3.8.9
* gcn-kafka==0.3.3
* confluent-kafka==2.2.0
* librdkafka 2.1.1 (homebrew install)

Note: I can replicate the same behavior by disabling my network connection and using a valid GCN domain (test.gcn.nasa.gov, gcn.nasa.gov). It's just easier to use the bogus domain for testing since I don't need to disable my network connection.

**Comment by dakota002** [comment]
Did https://github.com/nasa-gcn/gcn.nasa.gov/pull/1860 handle this issue? If not, what else needs to be done?

**Comment by lpsinger** [comment]
I think so.

**Comment by joshuarwood** [comment]
I checked the current Producer documentation on https://gcn.nasa.gov/docs/notices/producers and it is **not** sufficient to address an issue we saw in the GBM producer. This is due to a default producer config parameter `metadata.max.age.ms` that resets the metadata containing outgoing messages after 5 minutes. Using `producer.flush()` will wait unit the metadata resets and then quietly exit without sending the message. It will trick you into thinking the message was sent when it was not. To avoid this behavior in GBM we explicitly set `metadata.max.age.ms` to a timeout value + 1 second and then pass the timeout value to flush(). This ensures the flush command will always timeout before the metadata with the message resets.

**Comment by lpsinger** [comment]
What do you suggest? Unfortunately there is no unique "right" answer here; the settings are application dependent (see https://github.com/nasa-gcn/gcn.nasa.gov/issues/1545#issuecomment-1769170448).

**Comment by joshuarwood** [comment]
I agree that there isn't necessarily a right answer for all cases.

At the same time, I would say `producer.flush()` alone is a wrong answer because the [confluent_kafka documentation](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html) for flush notes the following: 

```
flush()
flush([timeout])
Wait for all messages in the Producer queue to be delivered. 
This is a convenience method that calls [poll()](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.poll) until len() is zero or the optional timeout elapses.
```
but `producer.flush()` will not wait until all messages are delivered in the GCN implementation due to the default `metadata.max.age.ms` setting.

A possible right answer would be to add a 1 min timeout with `producer.flush(60)` because this obeys the behavior a user will expect from that function. The producer will wait for 1 min to send the message and exit with a clearly defined error if the message could not be sent. There could be note about needing to mind the value of `metadata.max.age.ms`  when using timeouts 5 min or longer.
