### ISSUE TITLE
Remove links to Wikipedia

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#1590]
> It's a NASA policy when it comes to public communications to only link to trusted other agency or institution websites. Anyone can change the content of wikipedia.

Is there a link to that policy? I haven't heard of it before.

_Originally posted by @lpsinger in https://github.com/nasa-gcn/gcn.nasa.gov/pull/1540#discussion_r1364558007_

**Comment by jracusin** [comment]
https://communications.nasa.gov/socialmedia/guidance/linking-outside

**Comment by jracusin** [comment]
Addressed by PR #1588

**Comment by lpsinger** [comment]
No, I think that there still are some left.

**Comment by lpsinger** [comment]
The remaining links to Wikipedia pages are:

- https://en.wikipedia.org/wiki/Snake_case
- https://en.wikipedia.org/wiki/Content_delivery_network
- https://en.wikipedia.org/wiki/Serverless_computing
- https://en.wikipedia.org/wiki/Infrastructure_as_code
- https://en.wikipedia.org/wiki/Continuous_deployment

I don't know of a good alternative source to define these terms.
