### ISSUE TITLE
Increase duration of kafka record rate look back

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#1615]

**Comment by lpsinger** [comment]
I'll just increase the Kafka data retention duration itself. Currently it's set to one week. I'll slowly ramp it up to one month.

**Comment by lpsinger** [comment]
Updated to two weeks.

**Comment by jracusin** [comment]
Have you increased this further?

**Comment by lpsinger** [comment]
Increased to one month now.
