### ISSUE TITLE
broken Hyperlinks in the webpage 

### ISSUE THREAD

**Issue by tahumada** [nasa-gcn/gcn.nasa.gov#1662]
The Fermi links seem to be broken in the GCN webpage. 
It looks like the link only take the first line of the text into consideration
example: https://gcn.nasa.gov/circulars/35025

**Comment by lpsinger** [comment]
I think that this behavior is correct, because there isn't a safe way to distinguish between these two inputs:

```
A long link https://en.wikipedia.org/wiki/Grav
itational_wave
```

versus this:

```
A long link https://en.wikipedia.org/wiki/Gravitational_wave
and then more words
```

It might have gotten mangled and incorrectly word-wrapped by the submitter's email client.

I've fixed that Circular.
