### ISSUE TITLE
Sandbox for GCN Circular submissions

### ISSUE THREAD

**Issue by aleberti** [nasa-gcn/gcn.nasa.gov#1713]
It would be useful to have a sandbox environment where people can test sending GCN Circulars without distributing them to the world, but e.g. sending them back to the sender or a specified email address. It could be e.g. an additional email address different from circulars@gcn.nasa.gov, with which users can test if they have for example automated scripts to produce and send GCN Circulars. In that way, one can test the end-to-end process of the circular distribution.

(Inspired by the TNS Sandbox: https://sandbox.wis-tns.org/)

**Comment by aleberti** [comment]
By the way, I opened the issue here, I was not sure which is the best place for it. Feel free to move this in the place you find more appropriate! :)

**Comment by lpsinger** [comment]
Would our public test instance, https://test.gcn.nasa.gov/, satisfy your requirements? See https://gcn.nasa.gov/docs/contributing/deployment#stages.

**Comment by aleberti** [comment]
Yes! Sorry I did not looked at that particular page of the documentation. It is definitely what I was searching for! I already asked for endorsement to be able to submit test Circulars. I think the issue can be closed here. Thanks for the prompt help!
