### ISSUE TITLE
Schema Browser breadcrumb links are not pointing to the correct paths

### ISSUE THREAD

**Issue by dakota002** [nasa-gcn/gcn.nasa.gov#1721]
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/60568679-46dc-41c1-ae19-81e82caf6f82)

The paths seem to be parsing the `..` filled array relative to the base path of `/docs/schema/{version}`, and not the full path of `/docs/schema/{version}/*`

**Comment by lpsinger** [comment]
I thought that I added the [`relative="path"`](https://reactrouter.com/en/6.20.1/components/link#relative) attribute to fix this some time ago. Perhaps there has been a regression in Remix or react-router.

**Comment by lpsinger** [comment]
Yup, I think that this broke when we updated from remix 2.2.0 to 2.3.0.

**Comment by lpsinger** [comment]
I've reviewed the [diff between Remix 2.2.0 and 2.3.0](https://github.com/remix-run/remix/compare/remix%402.2.0...remix%402.3.0) and it looks pretty boring. On the other hand, there are some relevant looking changes in the following two dependencies that were updated in that version:

- https://github.com/remix-run/react-router/blob/main/packages/router/CHANGELOG.md#1120
- https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6190

**Comment by lpsinger** [comment]
Possibly https://github.com/remix-run/react-router/pull/11006...

**Comment by lpsinger** [comment]
Yup, this was broken by the fix of https://github.com/remix-run/react-router/issues/10998.
