### ISSUE TITLE
Add source for timeline figure to version control

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#1836]
> Where is the source artwork for this graphic? Is it an Adobe Illustrator file? A Python/matplotlib script? Can we get the source artwork under version control, please?

_Originally posted by @lpsinger in https://github.com/nasa-gcn/gcn.nasa.gov/pull/1805#discussion_r1442996181_

**Comment by Courey** [comment]
https://github.com/nasa-gcn/gcn.nasa.gov/pull/1839

**Comment by lpsinger** [comment]
> > Where is the source artwork for this graphic? Is it an Adobe Illustrator file? A Python/matplotlib script? Can we get the source artwork under version control, please?
> 
> _Originally posted by @lpsinger in [#1805 (comment)](https://github.com/nasa-gcn/gcn.nasa.gov/pull/1805#discussion_r1442996181)_

That's not the source material. That's the image itself. How was this image generated?

**Comment by Courey** [comment]
I know. That fixes the broken build, not the source issue. My same question still remains. I am not sure where the image is generated.

**Comment by Courey** [comment]
I believe the source is a keynote file currently. According to Daniel.

**Comment by dankocevski** [comment]
Yeah, the graphics was developed in Keynote. I'm not entirely sure the Keynote file belongs in the repo itself.

**Comment by lpsinger** [comment]
Alright, perhaps we could generate this programmatically from a JSON data file so that anyone can update it.

**Comment by lpsinger** [comment]
As for Keynote files in Git, there's no problem with that. When we author graphics in a desktop app, we do tend to keep the editable source file under version control. Here's an example: https://github.com/nasa-gcn/gcn.nasa.gov/tree/0e366e85d5ec2465fb6fa06a14578a6c419cf4e1/app/routes/_gcn.docs.contributing.email
