### ISSUE TITLE
Rate estimates for notices appear to be rounded to zero

### ISSUE THREAD

**Issue by titodalcanton** [nasa-gcn/gcn.nasa.gov#1857]
When I sign up for email notices on https://gcn.nasa.gov/user/email, I can select which notice types I want to receive. Each type has a rate estimate next to it. However, in many cases, this estimate is zero, for example I see

> SWIFT_BAT_GRB_POS_ACK 0 alerts per day

It would be useful to have the actual (nonzero) rate, like "0.1 alerts per day" or even better "1 alert per X" where "X" is automatically chosen to be day, week, month as appropriate.

Edit: I suppose some notice types really never had any notice yet. In that case it would be useful to see something like "Rate unknown as no notices submitted yet".

**Comment by lpsinger** [comment]
We do show different units for rates that are less than one day. Here's an example:

![Screenshot 2024-01-23 at 10 46 32](https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/2d56ab39-cafc-4ce5-9104-529df5292738)

We have a very small measurement period for the rate estimate, and rare alert types that do not show up during the measurement period are reported as zero.

**Comment by titodalcanton** [comment]
Thanks @lpsinger, that makes sense. Then may I suggest reporting "Less than 1 alert per <measurement period>" instead of "0 alerts per day"?

**Comment by lpsinger** [comment]
That's a great idea!
