### ISSUE TITLE
Front-end design for email notifications

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#187]
Storyboard (whiteboard is fine) for the following UI/UX related to email notifications:

1. [x] Navigation to email notification settings (user dropdown in navbar, user settings page)
2. [x] List of email subscriptions
3. [x] CRUD on email subscriptions
4. [x] Send test message
5. [x] Click to unsubscribe - and confirm, to protect from list unsubscribe. (Research what we have to do for common mail clients to present their built in "unsubscribe" option --- including the auth flow)

Definition of done: attach storyboard images to this issue.

**Comment by dakota002** [comment]
![Form](https://user-images.githubusercontent.com/11023698/181085488-a0831893-191a-4dfc-9146-67ebceaf6285.png)
![UserSetting](https://user-images.githubusercontent.com/11023698/181085489-7a08eaa6-2740-44e2-8c42-eeff004b4c37.png)

Rough design ideas

**Comment by dakota002** [comment]
Here are some screenshots of the new UI.

/user page
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/11023698/181351919-c95b461f-d1ed-4fdd-8f2a-c48d294ea434.png">

Credential Pages:
/user/credentials
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/11023698/181365804-c89c45b6-63b6-4a54-8aff-01c8a065434d.png">

/user/credentials/edit , might change the edit here to 'add' or 'new'
(should look familiar)
<img width="948" alt="image" src="https://user-images.githubusercontent.com/11023698/181366052-8dbbae9a-1421-4aaa-a401-f94bc9eda5cf.png">

Notice management pages:
/user/notifications
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/11023698/181351420-759974ec-c197-464b-b07f-13e85c73a6ec.png">

/user/notifications/edit
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/11023698/181351605-a9d4a3ce-9e96-461b-8c6c-2c05f36fbb2d.png">

**Comment by dakota002** [comment]
@lpsinger and @jracusin let me know what you think

**Comment by lpsinger** [comment]
Holy moly this looks nice. I'll send detailed feedback later.

**Comment by lpsinger** [comment]
A couple suggestions:

1. [ ] Make sure that the page title in the sidenav matches the header in the page content.
2. [ ] I prefer "Client Credentials" because although it is a little longer than just "Credentials" it is technically accurate in that these are, in fact, OIDC client credentials.
3. [ ] I prefer the title "Email Notifications".
4. [ ] For completeness, add a signout link in the sidenav.
5. [ ] Turn the Add link into a button.
6. [ ] Try out adding icons for Add, Delete, Edit, and Test.
7. [ ] For time created, render as "x seconds ago" using Moment.js.
8. [ ] Too much vertical whitespace between Recipient, Notice Format, Notice Types.

**Comment by dakota002** [comment]
Here is an update to the UI, 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/11023698/181767056-2277d51b-f4c9-4121-a66b-a00b70ebbd9d.png">

Some styling for mobile
![image](https://user-images.githubusercontent.com/11023698/181767232-088eae3f-56f8-4ebc-b417-cbf766fcad53.png)

**Comment by lpsinger** [comment]
Looks great. I do like the button icons. A few more suggestions:

* [ ] Ditch the checkbox icon.
* [ ] On sufficiently wide screens, have the Add button appear on the same line as the heading.

**Comment by lpsinger** [comment]
The one thing I'm a little worried about is that the Account Info page seems very bare. Eventually this would be a good place for reset password, link accounts, etc. In the meantime, we should put just a little bit of content there. Any ideas?

**Comment by dakota002** [comment]
@lpsinger I agree it is a bit empty. I think for now it is fine to be empty, and if we want we could just not show it yet. I think in the future it would make sense to add the account stuff you listed, but for the purpose of this PR/issue I think it should be as is

**Comment by lpsinger** [comment]
> If we want to show content, maybe just a call out to the links in the bottom for them to request features/info to be displayed there?

👍
