### ISSUE TITLE
Implement Kafka to email bridge

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#189]
1. [x] Decide on implementation strategy:
    * a Docker container that is always running, subscribing to all public topics, and making AWS API calls? 
    * use an existing AWS service to bridge Confluent Kafka to something that can trigger Lambda invocations?
    * bridge directly to something that can trigger email notifications? (e.g. Kafka -> SQS -> SNS -> email)
2. [x] Subscribe to necessary Kafka topics
3. [x] Read subscription data
4. [x] Send emails

Depends on #185, #186, #188.

**Comment by dakota002** [comment]
https://github.com/nasa-gcn/gcn-email-service

I have spent some time setting this up, it works locally with hard coded values, but I would like to get it out on dev along with the front end update for the subscriptions

**Comment by lpsinger** [comment]
Renamed to: https://github.com/nasa-gcn/gcn-email

Let's keep this open until everything is set for deployment to prod.
