### ISSUE TITLE
ACROSS API/BurstCube MVP - create accessibility for BurstCube api scopes. 

### ISSUE THREAD

**Issue by swyatt7** [nasa-gcn/gcn.nasa.gov#1901]
We need the ability to test our BurstCube API endpoints with the Bearer Authentication. Thus we need the functionality to create a user client with the credentials containing the scope `"write:/bustcube_too"`. This scope will then be decorated on the `POST`, `PUT`, and `DELETE` endpoints.

**Comment by lpsinger** [comment]
Currently, our custom scopes are implemented using [Cognito resource servers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-define-resource-servers.html), so they must have the format `resourceServerIdentifier/scopeName`. The value of `resourceServerIdentifier` is `gcn.nasa.gov`, so our scopes have names like:

```
gcn.nasa.gov/circular-submitter
gcn.nasa.gov/circular-moderator
gcn.nasa.gov/kafka-einstein-probe-producer
```

I don't know why the Cognito custom scope names and the SciTokens claim names differ in format, but for the short term we should just create a custom scope using the format above. What should we call it?

**Comment by swyatt7** [comment]
Since we will be using Cognito, we should stick with their format. I'm OK with something like:

```
across.nasa.gov/burstcube-too-post
```

of since we will still be in GCN, I'm ok with:

```
gcn.nasa.gov/burstcube-too-post
```

Let me know what you think @lpsinger, @jak574.

**Comment by lpsinger** [comment]
My 2¢:

- There are a few places in https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/routes/_gcn.user.credentials/client_credentials.server.ts that we would need to change to support a resource server name other than `gcn.nasa.gov`, in addition to creating a new resource server.
- Most of our scope names are noun phrases. For consistency, could we use `burstcube-too-submitter` rather than `burstcube-too-post`?

Given the above, would you be OK with `gcn.nasa.gov/burstcube-too-submitter`?

**Comment by swyatt7** [comment]
`gcn.nasa.gov/burstcube-too-submitter` works for me!

**Comment by jak574** [comment]
`gcn.nasa.gov/burstcube-too-submitter` is good.

**Comment by lpsinger** [comment]
@dakota002, would you please provision these groups and scopes, and coordinate with @jracusin on who should belong to these groups on dev, test, and prod?

**Comment by jracusin** [comment]
For now, please add @aam97 and me.

**Comment by dakota002** [comment]
Should be all set. Please let me know if there are any issues
