### ISSUE TITLE
Deployment failing (Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes ...)

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#1974]
This deployment job failed: https://github.com/nasa-gcn/gcn.nasa.gov/actions/runs/8009926080/job/21879698424

In our CloudFormation stack, the resource AnyLabsApiCatchallHTTPLambda is failing to update with the following error message: `Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes ...`

**Comment by lpsinger** [comment]
It look like this broke in #1472.

**Comment by lpsinger** [comment]
@jak574's concern about the dependencies pulled in by Healpy were well-founded. Here are the largest vendored packages, with sizes in MiB:

```
$ du -m -d 3 * | sort -rn
107	scipy
70	healpy
58	astropy
41	matplotlib
36	numpy
27	numpy.libs
27	fontTools
26	scipy.libs
19	scipy/stats
16	numpy/core
15	astropy/io
14	scipy/sparse
14	cryptography/hazmat
14	cryptography
13	scipy/special
13	scipy/optimize
13	cryptography/hazmat/bindings
12	scipy/linalg
12	healpy.libs
11	pillow.libs
10	matplotlib/mpl-data
9	matplotlib/mpl-data/fonts
9	astropy_iers_data/data
```

**Comment by lpsinger** [comment]
A lot of that space is taken up by test data. If I delete all the test data, that helps but doesn't get us far enough: we only get down to 431 MiB.

```
$ du -m -d 0 * | sort -rn | head -n 20
80	scipy
70	healpy
38	astropy
36	matplotlib
27	numpy.libs
27	fontTools
26	scipy.libs
21	numpy
14	cryptography
12	healpy.libs
11	pillow.libs
9	astropy_iers_data
7	PIL
6	kiwisolver
5	shapely.libs
5	shapely
5	pydantic_core
4	pydantic
4	erfa
3	yaml
```

**Comment by lpsinger** [comment]
Numpy and Scipy each provide copies of openblas and libgfortran. We could save about 26 MB if we could deduplicate it.

Healpy may be statically linked against the healpix-cxx library. Since it contains several extension modules, we can probably reduce its size by up to 50 MiB by making sure it is dynamically linked and only includes one copy of the underlying healipx-cxx object code.

**Comment by jak574** [comment]
Right now scipy is only being used for the `normpdf` function. I already wrote my own version of this because I was concerned about adding such a huge dependency for one function. I'm sure we can get this from either somewhere else, or just use our own function. That'd save us a big chunk of MBs.

**Comment by jak574** [comment]
If there's a way to have healpy without the matplotlib dep, that would save a lot also.

**Comment by swyatt7** [comment]
I agree with @jak574  in removing scipy, re-adding gthe `normpdf` function, and seeing where that gets us.

**Comment by dakota002** [comment]
> > Also now that healpy is a dependency windows builds crash
> 
> Yes, @dakota002, I know. As a temporary workaround, you can comment out `healpy` from requirements.txt.

Okay cool, I'm still working on the windows build btw. Will let you know when I have made some significant headway
