### ISSUE TITLE
experiment with execa signal handling

### ISSUE THREAD

**Issue by Courey** [nasa-gcn/gcn.nasa.gov#2010]
### Description

Execa has a cleanup option defaulted to true. When true processes are killed automatically when the parent is terminated. 
[link to the execa default](https://github.com/sindresorhus/execa?tab=readme-ov-file#cleanup)

The purpose of this experiement is:
Our theory is that execa's cleanup behavior is racing against the cleanup behavior that we were trying to add to remix dev. Execa is winning and the process is already dying by the time our handler runs.

to test this theory we need to set cleanup to false in remix dev where it uses execa to call run arc sandbox. we also need to add a handler to remix dev that awaits the graceful termination of the child process. 

and we need to add an async exit handler to arc sandbox.

If we do all these things and this theory is correct, then docker should exit gracefully when we kill -2 or kill -15 remix dev. 

Acceptance Criteria:
documentation of the conditions of this test
showing the patches applied and where applied
the result of this test (yes or no)

**Comment by Courey** [comment]
![Image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/792fdd88-69b0-44d2-941f-5ca28331d24f)
![Image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/cef66946-5413-4e03-b130-2d2631b82f79)
![Image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/0e47cb6a-5275-4ed5-b378-a0346d5be8af)
![Image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/d27f5fbc-f613-42fb-8481-829e40492e61)

Results of preliminary testing:
- Changing the defaulted cleanup key to false does not have any impact on the observed behavior. 
- Once I changed that value, I ran it with no other changes. That did not impact shutdown, it still did not close gracefully. 
- After that experiment I commented out the existing exit handling and added signal handling for both the main process and the sub-process to observe what signals are being sent to each.
- I can observe and catch a SIGINT in the main process. 
- I can manually send a SIGINT to the child process. However, the only signal I observe being handled in the sub-process is an exit event, NOT a SIGINT. 
- I then ran an experiment where I got the sub-process' PID at startup and sent a SIGINT directly to that sub-process. It does NOT catch a SIGINT though, it catches an exit event.

My analysis at this point is that the main issue is with Architect. For reasons unknown it seems like it will not handle a SIGINT.

**Comment by lpsinger** [comment]
@Courey, remember that arc sandbox _does not have a sigint or exit handler_. It actually listens for control-C _as a keyboard input_, so it is ignorant of symbols --- hence https://github.com/architect/sandbox/pull/729. To complete this experiment, you need to patch _both_ @remix-run/remix-dev _and_ @architect/sandbox to perform signal handling. Did you remember to do the latter?

**Comment by Courey** [comment]
Yup! I did both. If you look at the last image attached to the last comment, you can see that the file I added signal handling to (mostly for commenting what the signal was) is architect/sandbox/src/arc/index.js

I also added exit-hook and tried that as well with no improved results as seen below.
![Image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/0bc2008d-9b2c-47e0-99d1-36ba142c485a)

Then I called for help. I created this ticket in architect https://github.com/architect/architect/issues/1479
they felt like it's related to the process being started by execa.[ this line in particular](https://github.com/sindresorhus/execa/blob/427c5c2011e365a274dcca1162334a51c7218bfc/lib/kill.js#L101). 

I messaged you in late February looking at execa causes since that's where I kept ending up, so that wouldn't surprise me if that is the cause. It's the whole child of a child of a child thing that I was talking about. It just goes one child deep and then nukes the rest.
