### ISSUE TITLE
ensure that feature flagged moderation works

### ISSUE THREAD

**Issue by Courey** [nasa-gcn/gcn.nasa.gov#2012]
### Task
- ensure that the code that is on production is in develop. 
- ensure that the feature flag being removed on develop works
- ensure that user is able to sign in
- ensure a signed in user is able to easily find and navigate to a circular
- the user can directly edit, submit a change request, and approving and rejecting different change requests, appropriate confirmation should be displayed after each action is done.
- ensure that on production none of this is accessible

**Comment by Courey** [comment]
This ticket is blocked by https://github.com/nasa-gcn/gcn.nasa.gov/issues/1974

**Comment by lpsinger** [comment]
#1974 is fixed. I've deployed to dev and test.

**Comment by lpsinger** [comment]
Moderation is currently activated on dev and deactivated on test. I've tested that things work as expected with the feature flag deactivated.

I see a few gaps when it is activated:
- [ ] #2065
- [ ] #2066

**Comment by lpsinger** [comment]
We already removed the feature flag.
