### ISSUE TITLE
research and integrate pointing poker for slack

### ISSUE THREAD

**Issue by Courey** [nasa-gcn/gcn.nasa.gov#2015]
## Issue
We need some way to point tickets async. Leo has a strong preference for open source. 

## Acceptance Criteria
- fully research the background of any slack integration options for pointing poker
- ensure there are not code vulnerabilities
- research the integration to make sure it's a known app maker
- ensure we are using app that we think we are
- integrate pointing poker in slack

**Comment by lpsinger** [comment]
> Leo has a strong preference for open source.

Not exactly: we need to do supply chain risk management due diligence because this tool may have access to both our GitHub org and our Slack workspace. If the tool is _not_ from a major supplier then it will be easier to audit if it is open source.

**Comment by dakota002** [comment]
@Courey @lpsinger 

Looked into a few, but this one seems pretty solid: https://deniz.co/slack-poker-planner/

I am a fan of their privacy policy:
> Apart from that, I get lots of question about privacy, so I want to clarify what the app can and cannot do:
The app does not know anything about your channels/conversations until you explicitly add the bot user to it.
Even if the bot is added to a channel, the only data that Slack sends to the app is channel id and channel name. Getting additional information (topic, member list, etc.) requires another permission that the app doesn't have.
The app cannot read any of your messages, even if the bot is added to that channel/conversation! The only thing the app can read is the poker planning session title you enter while using the app.
The app cannot list the users in your team workspace. When a user interacted with the app (create a new session, use a vote, etc.), Slack sends just user id and user name, nothing more.

I read over their repo a bit too, it looks good to me.  If either of you want to take a look: https://github.com/dgurkaynak/slack-poker-planner

What are both of your thoughts on this? If you're both on board we can add it to slack here  https://nasa-gcn.slack.com/apps/A57FFS3QE-poker-planner?tab=more_info

**Comment by lpsinger** [comment]
According to their features:

> Auto-reveal after voting ends (min 1 minute, max 7 days)

It seems to me like we usually take less than 1 minute to vote during meetings, what do you think?

**Comment by dakota002** [comment]
I agree, this feature is probably taking into account an async voting process where we just have until a certain day (usually the next planning session) to estimate the issue

**Comment by lpsinger** [comment]
Would you please check if that is the case, if we can end voting quicker than 1 minute, or see the results live as people vote, when we are doing live meetings?

**Comment by dakota002** [comment]
Oh yea, it has a "Reveal" button that the runner can see. 

From their demo clip:
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/5c841824-4249-4457-94a1-a35f9fc57add)

**Comment by lpsinger** [comment]
I like it. Let's use it!

**Comment by lpsinger** [comment]
Is this done now? Can we close it?
