### ISSUE TITLE
Add options for einstein probe in the UI

### ISSUE THREAD

**Issue by Courey** [nasa-gcn/gcn.nasa.gov#2031]
### Description
acceptance criteria:
- the quickstart form should have checkboxes for einstein probe notices.
- link to internal mission pages (draft PR for the mission pages)
- put behind feature flag until we're ready to announce

**Comment by jracusin** [comment]
EP mission page PR #2011

**Comment by jracusin** [comment]
Separated out SVOM and BurstCube into their own tickets.
