### ISSUE TITLE
Document open port for Kafka client

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#205]
@genghisken and @DrPhilEvans both report that their institutions block egress on TCP/IP port 9092, which is required for Kafka client.

As a start, we should document the required ports on our web site so that they can point their institutions' IT staff to our docs as proof that they need an exception.

We might want to think about enabling the [Confluent REST Proxy](https://docs.confluent.io/platform/current/kafka-rest/index.html) as well.

**Comment by lpsinger** [comment]
Closed by mistake.

**Comment by lpsinger** [comment]
@genghisken, @DrPhilEvans, is the following new FAQ entry sufficient for your institutions' IT departments to unblock the required ports?

https://gcn.nasa.gov/docs/faq#what-ports-do-i-need-to-open-in-order-to-receive-or-send-gcn-notices-with-kafka

**Comment by genghisken** [comment]
Looks fine to me!  Thanks Leo!

**Comment by DrPhilEvans** [comment]
Yep, that's great, thanks.

P

On 04/08/2022 20:29, Leo Singer wrote:
>
> 	
> ****CAUTION:**** This email was sent from an *EXTERNAL* source. Think 
> before clicking links or opening attachments.
> 	
>
> @genghisken 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgenghisken&data=05%7C01%7Cpae9%40leicester.ac.uk%7C6baf2b53c27f4cda6b6a08da764f9668%7Caebecd6a31d44b0195ce8274afe853d9%7C0%7C0%7C637952381442144188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VujSF3YXRgBBF22eqZ9HwWnGHO%2F97GBqeLKRYOYcfTE%3D&reserved=0>, 
> @DrPhilEvans 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDrPhilEvans&data=05%7C01%7Cpae9%40leicester.ac.uk%7C6baf2b53c27f4cda6b6a08da764f9668%7Caebecd6a31d44b0195ce8274afe853d9%7C0%7C0%7C637952381442144188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JHBvACgn%2FTpwV28boPF8SfchiQF8qkGLTopXXt3o7iI%3D&reserved=0>, 
> is the following new FAQ entry sufficient for your institutions' IT 
> departments to unblock the required ports?
>
> https://gcn.nasa.gov/docs/faq#what-ports-do-i-need-to-open-in-order-to-receive-or-send-gcn-notices-with-kafka 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcn.nasa.gov%2Fdocs%2Ffaq%23what-ports-do-i-need-to-open-in-order-to-receive-or-send-gcn-notices-with-kafka&data=05%7C01%7Cpae9%40leicester.ac.uk%7C6baf2b53c27f4cda6b6a08da764f9668%7Caebecd6a31d44b0195ce8274afe853d9%7C0%7C0%7C637952381442144188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZhewWYejI0C0a1biqVEdkJV2fD9frxWr6Hpgaubw7QQ%3D&reserved=0>
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnasa-gcn%2Fgcn.nasa.gov%2Fissues%2F205%23issuecomment-1205683244&data=05%7C01%7Cpae9%40leicester.ac.uk%7C6baf2b53c27f4cda6b6a08da764f9668%7Caebecd6a31d44b0195ce8274afe853d9%7C0%7C0%7C637952381442144188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vpFYGQ9lvWFjNrXV%2BYVUBrWaaoqnSJ2DgIMjUoNp8R4%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABDV4WAA663VTD3ATPMNKKLVXQKX3ANCNFSM55LE7SGA&data=05%7C01%7Cpae9%40leicester.ac.uk%7C6baf2b53c27f4cda6b6a08da764f9668%7Caebecd6a31d44b0195ce8274afe853d9%7C0%7C0%7C637952381442144188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nK4NJpgPVkz34Akb6O9UjpverEPqFwNp5fQMOKmwsaE%3D&reserved=0>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

-- 
-------------------------

Phil Evans,
Swift Development Scientist & Athena W-ISC Technical Lead
X-ray and Observational Astronomy Group,
University of Leicester

Tel: +44 (0)116 252 5059
Mobile: +44 (0)7780 980240 (work)
Mobile: +44 (0)7974 977723 (personal)

***@***.***

http://www.star.le.ac.uk/~pae9
http://www.swift.ac.uk

Follow me as a Swift scientist on Twitter: @swift_phil
http://www.star.le.ac.uk/~pae9/twitter
