### ISSUE TITLE
Moderation reject button failing

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2096]
I have only tried this on dev, but when I select the "Reject" button, while logged in, it gives me an error that tells me to login, but logging in doesn't help.
<img width="994" alt="Screenshot 2024-03-14 at 1 19 32 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/a01702eb-bc40-441d-997d-50ddadf19e4a">
<img width="983" alt="Screenshot 2024-03-14 at 1 19 42 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/f782c3f8-accd-4032-af7a-bd83975c477a">

**Comment by jracusin** [comment]
Note that I have successfully approved corrections on dev.

**Comment by dakota002** [comment]
I think i found the issue, its an `||` that should be a `&&`
