### ISSUE TITLE
Ticketing system

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#211]
We need a system to track users asking for unsubscribing to GCN Classic once Email Notifications is rolled out through the new GCN.  Need better tracking that people emailing Scott.  This could also be used for GCN Circulars until they are overhauled.

**Comment by lpsinger** [comment]
I think that we just need a general ticketing system, and this can be one of many categories. @trjaffe, how is your trade study going?

**Comment by jracusin** [comment]
Right, that's fair.  Just wanted to have an issue to track on this.

**Comment by trjaffe** [comment]
I'm waiting for a response from some system folks about whether this can be done on GitLab.  I'll nudge them.

**Comment by lpsinger** [comment]
I have used [GitLab Service Desk](https://docs.gitlab.com/ee/user/project/service_desk.html) and it is quite nice.

**Comment by lpsinger** [comment]
Closing this, as we have adopted Zendesk.
