### ISSUE TITLE
Add announcements section

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#215]
We can remove the webinar banner advertising past webinars.  Though we should keep the link to the presentation somewhere prominent and also link the recording.

**Comment by dakota002** [comment]
I've spent some time looking through the sites listed under the Showcase section of the USWDS page. 
The [pub med](https://pubmed.ncbi.nlm.nih.gov/) page has a section we could try to emulate, or take some inspiration from.

![image](https://user-images.githubusercontent.com/11023698/183978231-6ee48f06-3c18-4d4c-8137-9f1ed41161e1.png)

Whereas the [plainlanguage](https://www.plainlanguage.gov/) page opts for a section styled more like this:

![image](https://user-images.githubusercontent.com/11023698/183978528-5ef5b4ba-abd6-46a6-b465-5447a302f371.png)

I think the latter is somewhat more in line with our current design. I will also throw the idea out there of converting the hero section into a carrousel style UI component, which could lead with the latest news first, and just loop through the N most recent items.

There is also the [collections](https://designsystem.digital.gov/components/collection/) component which we could use. 

Any opinions on which may work best for us?

**Comment by lpsinger** [comment]
I like the latter.

**Comment by dakota002** [comment]
How is something along the lines of this for a news section?

![image](https://user-images.githubusercontent.com/11023698/184239341-b290dbc5-1677-4e08-bd3b-61274195bc7b.png)

Pretty rough draft based on the latter of the two examples

**Comment by lpsinger** [comment]
Can you show this in context of the whole page?

What about https://designsystem.digital.gov/components/collection/?

**Comment by dakota002** [comment]
Just below the table
![image](https://user-images.githubusercontent.com/11023698/184366522-aab5ffc9-1d31-4933-a234-5767a3a19b71.png)

 and the end, 

![image](https://user-images.githubusercontent.com/11023698/184366648-fb1b5f2f-0bc0-470a-97aa-0b19b420b9e5.png)

**Comment by lpsinger** [comment]
I don't like that you have to scroll all the way down to the bottom to see the news.

**Comment by dakota002** [comment]
Think it might be better at the top? Or just earlier on in the page? 

Also would you like me to implement it as the uswds collection?

**Comment by lpsinger** [comment]
I'd like to see what the collection version looks like.

gsa.gov has a nice way of packing news items into a single column of two columns:

<img width="1115" alt="Screen Shot 2022-08-12 at 11 52 40" src="https://user-images.githubusercontent.com/728407/184394717-8606f7bb-7953-49b4-912a-c9077dd967fc.png">

Do we have any other content that would make sense to put in a column next to it?

**Comment by dakota002** [comment]
I dont know what should go there now, do we have any events or news?

**Comment by lpsinger** [comment]
The webinar!

**Comment by lpsinger** [comment]
Left.

**Comment by jracusin** [comment]
I like it with the short description on the left, but I still don't quite see how this fits in context of the whole page.  I'll work on drafting those news items.  Do you have a file in this format that I can edit or should I just make a md?

**Comment by dakota002** [comment]
RIght now the content for that section is just an object in the NewsSection.tsx

**Comment by dakota002** [comment]
@jracusin Just added my branch in a draft PR
