### ISSUE TITLE
make light design doc for synonyms

### ISSUE THREAD

**Issue by Courey** [nasa-gcn/gcn.nasa.gov#2164]
## Description
We need a design doc for synonyms. This shouldn't be a super in depth design doc, but should cover all the actions and the basic design and data structures.

## Acceptance Criteria
- a lightweight design doc for synonyms is created
- - it has pseudo code for all actions

**Comment by lpsinger** [comment]
You might also want to analyze the number of queries, rows modified, and rows returned for each action.

**Comment by Courey** [comment]
https://gist.github.com/Courey/aba6a56d2746ea64cd1f68a04b1c4b9f

**Comment by Courey** [comment]
@lpsinger I wasn't sure where to put this, so I created a gist. Let me know if you need more/different sections or want it moved elsewhere.

**Comment by lpsinger** [comment]
> @lpsinger I wasn't sure where to put this, so I created a gist. Let me know if you need more/different sections or want it moved elsewhere.

That's a great place for it for now. I'm fairly constrained for time this week due to APS, but if I don't read and comment it by COB this Monday than I owe you a {beer,tea,coffee,beverage of choice}.

**Comment by lpsinger** [comment]
@Courey, I'm resolving this, since you and I agreed on a design on Monday.
