### ISSUE TITLE
BurstCube SVG logo

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2167]
We do not have a SVG version of the image, only a PDF, and I've tried to convert to SVG, but have only come up with a very distorted version. If you have a good way to convert, I can send you the pdf.

_Originally posted by @jracusin in https://github.com/nasa-gcn/gcn.nasa.gov/pull/2152#discussion_r1546369558_

**Comment by lpsinger** [comment]
Yes, I do, please send me the PDF.

**Comment by lpsinger** [comment]
This file was created by Adobe Illustrator. Do you have the original Adobe Illustrator file? If not, do you know who made this logo?
