### ISSUE TITLE
Schema browser returns unexpected error

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2174]
# Current behavior
Schema Browser returns error
![Screenshot 2024-04-02 at 3 41 10 PM](https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/75ee0e72-10f5-4dcb-b846-e3e28af960b5)

# Expected behavior
https://gcn.nasa.gov/docs/schema should take me to the schema browser

# Steps to reproduce
visit https://gcn.nasa.gov/docs/schema

# Environment
Safari on Mac M2 OSX 13.6.4

**Comment by lpsinger** [comment]
Fixed.
