### ISSUE TITLE
User Feedback on Astro Flavored Markdown

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2198]
# Description
Reach out to frequent Circulars users and ask them to try out astro-flavored markdown on test.gcn.nasa.gov

# Acceptance criteria
- Users provide feedback
- We implement changes

**Comment by jracusin** [comment]
Email/slack to send to teams to test:

Hi [group],
Would you be willing to test out the pre-release GCN Circulars Astro-flavored markdown feature?  This will be part of our Circulars submission web form that makes it easier to format data and embed content, like tables.  It works a lot like GitHub markdown, with some customization, like automatically linking to other GCN Circulars and common astronomy sources.

It's not yet live on the production GCN system, but can be accessed on our test system at https://test.gcn.nasa.gov/circulars/new.  Please play around with it, and post any feedback on https://github.com/nasa-gcn/gcn.nasa.gov/issues/2198.  There's documentation, on which we'd also appreciate feedback (https://test.gcn.nasa.gov/docs/circulars/markdown).

Using the Test GCN website:
- If you haven't already done so, you'll have to create an account.  It can be the same login method as your production GCN credentials, but you'll have to do that account creation again for Test.
- You'll also have to do the peer endorsement again.  Feel free to enter me as your endorser.  
- You can also go into your user profile and unsubscribe from receiving test Circulars.
- Note that any Circulars you submit on Test will only be distributed to other people who have accounts on test, and they'll be clearly marked as tests.

Thanks,
[name] for the GCN Team

**Comment by lpsinger** [comment]
Would you please put this in the drafts repo?

**Comment by jracusin** [comment]
Here's a link to the feedback request in the announcements repo.

https://github.com/nasa-gcn/announcements/blob/main/gcn-new-features/astroflavored-markdown-feedback.txt

**Comment by jracusin** [comment]
It's already merged and deployed.  Not seeking feedback before release.

**Comment by lpsinger** [comment]
We still do need user feedback...
