### ISSUE TITLE
Switching Notice Format When setting up Notice Stream resets selection

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2224]
# Current behavior
When setting up a new notice stream and customizing alerts (step 3), switching between notice formats resets the selected notice types.

# Expected behavior
Switching from one notice format to another should retain selected notice types if they're available in the new format. Potentially have a fading tooltip to indicate that some notices that were selected aren't available in the other format type if that is the case.

# Steps to reproduce
1. initiate a new notice stream setup
2. proceed to step 3
3. select one or multiple notice types
4. switch to another notice format
5. the selected notice types will be reset

# Environment

Chrome, MacOS

**Comment by tylerbarna** [comment]
Tangential issue: clicking one of the details links for a notice type opens the documentation in the same page; returning to the page results in all links being unselected as well

**Comment by lpsinger** [comment]
Won't fix.
