### ISSUE TITLE
Clicking details link when setting up notices streaming navigates to documentation on same page

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2225]
Tangential issue: clicking one of the details links for a notice type opens the documentation in the same page; returning to the page results in all links being unselected as well

_Originally posted by @tylerbarna in https://github.com/nasa-gcn/gcn.nasa.gov/issues/2224#issuecomment-2073110376_

**Comment by Kaustavpal007** [comment]
The refresh rates are very low and few sites are not open.
