### ISSUE TITLE
Add GECAM notice types

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#223]
- [x] Add kafka topics for GECAM_FLT NOTICE, GECAM_GND NOTICE to gcn-kakfa
- [x] Add kafka topics to "getting started guide"
- [x] Add GECAM Mission page

**Comment by dakota002** [comment]
I added a new branch and have a WIP PR for the 2nd and 3rd tasks. I don't have the content for the GECAM mission page though. @jracusin do you have some content I can copy into it?

**Comment by jracusin** [comment]
@dakota002, yes, I have the draft announcement.  I'll send you the link on Teams.  We can extract info from that, using a similar format as the other missions.

**Comment by lpsinger** [comment]
@jracusin, please note the edits in #224 and make sure that you keep the draft announcement up to date with them.

**Comment by jracusin** [comment]
@lpsinger please make sure the updates in pygcn with these notice types are running.  The topics should be available now, but do not appear to be.
