### ISSUE TITLE
"node / build (22, windows-latest)" Check failing on all PRs

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2242]
# Current behavior

All PRs are currently failing the "node / build (22, windows-latest" check at the NPM install step. Example failed check can be found [here.](https://github.com/nasa-gcn/gcn.nasa.gov/actions/runs/8881342274/job/24383461345?pr=2238#logs)

Seems to have started after 3cdd476ee6f9b7188ac5ab6f49176a34710a576a

# Expected behavior
Check not failing

# Steps to reproduce
- Make a commit in a PR
- It will fail 

# Environment
Github

**Comment by lpsinger** [comment]
Reported upstream as https://github.com/actions/setup-node/issues/1025.
