### ISSUE TITLE
Announcement for GCN email notification service

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#226]
1. [x] Draft the announcement text for the web site.
2. [x] Load it into the announcements section (depends on #215).
3. [x] Optionally, add a site banner like we did for the webinar. (Is there an equally visible but less cloying way to highlight the most recent announcement?)
4. [ ] Draft and send GCN Circular.

**Comment by jracusin** [comment]
On the email service setup page, @dakota002 please add the following:

To unsubscribe from your GCN Classic Notice subscriptions, please [send us a message](https://heasarc.gsfc.nasa.gov/cgi-bin/Feedback?selected=gcnclassic).

**Comment by dakota002** [comment]
How's this?
![image](https://user-images.githubusercontent.com/11023698/188193420-cb74f855-e00d-4c50-8195-2a2bbf081e48.png)

**Comment by jracusin** [comment]
Looks good to me.
