### ISSUE TITLE
Schema browser not updating with new tagged version

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2276]
# Current behavior

Schema browser takes you to v3.0.0, rather than v4.0.0

# Expected behavior

Schema browser should take you to latest tagged version.

# Steps to reproduce

# Environment

**Comment by lpsinger** [comment]
The latest version is 3.0.0. See https://github.com/nasa-gcn/gcn-schema/releases...

<img width="1157" alt="Screenshot 2024-05-13 at 11 42 16" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/b17e64c4-437f-4548-a417-77934935b17a">

**Comment by dakota002** [comment]
It is working as expected, I ran `git push` but forgot to include `git push origin v4.0.0`
