### ISSUE TITLE
Expand sample code documentation on parsing notices

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2278]
# Description

During course of the Hot Wiring the Transient Universe GCN streaming demo, it was suggested that we expand some of the documentation regarding parsing notices in various formats. Currently, the documentation is listed [here,](https://gcn.nasa.gov/docs/client/samples) but it is specific to xml notices 

# Acceptance criteria

- [ ] Provide example code for parsing the different available file formats
- [ ] (very optional, unsure of real world utility) create dummy topics so users can experiment with their code without having to wait for notices to stream in from real topics. could have them post every minute or something along those lines.

**Comment by tylerbarna** [comment]
Could potentially have a jupyter notebook included in documentation for new users and demos (not sure if this should be a separate issue)

**Comment by lpsinger** [comment]
Isn't this a duplicate of #2149?

**Comment by tylerbarna** [comment]
> Isn't this a duplicate of #2149?

yes it is, missed that
