### ISSUE TITLE
Link to notice type description

### ISSUE THREAD

**Issue by igorandreoni** [nasa-gcn/gcn.nasa.gov#228]
In the "Customize Alerts" step (3 of 4) of the "Start Streaming GCN Notices" process, it would be nice to have a link to each mission notices description directly on the page, or a sentence that says where you can find it (i.e., the "Missions" tab). I spent quite some time navigating the documentation before someone (Leo) told me where I should look instead.

**Comment by dakota002** [comment]
How about something like this, simplest solution, just expanding on the wording of that section

![image](https://user-images.githubusercontent.com/11023698/186731819-d119ced1-7af0-47fc-a7ea-9eda1c3a058f.png)

**Comment by lpsinger** [comment]
I don't see the links. Scroll down on the page and post a new screen shot?

**Comment by dakota002** [comment]
No links, just added wording to the main text block

**Comment by igorandreoni** [comment]
That is already better, thanks @dakota002

**Comment by lpsinger** [comment]
Would you please humor me and try out how this would look with a hyperlink in each of the top-level checkbox labels?

Remember that we also want to have, next to each notice type in the checkbox list, the approximate alert rate and data rate. So there will be a natural place for a "details" link in the checkbox list.

**Comment by dakota002** [comment]
Here's a quick preview of that, alignment is a little off at the moment because of the margin on the Labels, but this is the general idea right?

![image](https://user-images.githubusercontent.com/11023698/186740303-0acde25f-a196-4f53-b552-3dcf00132632.png)

**Comment by lpsinger** [comment]
Yeah, I like that. Maybe put it in parentheses?

**Comment by dakota002** [comment]
Got it aligned, do you think it should be in small tags or is the size good?
![image](https://user-images.githubusercontent.com/11023698/186748203-7fbf840b-271a-4181-a800-42b71dce480b.png)

**Comment by dakota002** [comment]
Some of the top level nodes do not have specific pages under our Missions section, 
BeppoSAX
HETE-2
IPN
RXTE 
and Other,
What should these link to?

**Comment by lpsinger** [comment]
Good question. BeppoSAX, HETE-2, IPN, and RXTE are no longer active, though.

**Comment by lpsinger** [comment]
OK, for now, since we don't have links for all of these missions yet, for now let's just have the paragraph at the top. But we should open a follow-up issue to add mission pages for the retired missions.

**Comment by dakota002** [comment]
Sounds good to me!
