### ISSUE TITLE
'Counterpart' Notice is incorrectedly labelled on website

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn.nasa.gov#229]
The 'Notices' page on the website lists:
"Swift Counterpart: Swift counterpart candidates of LVK events"
In reality, this is a general counterpart notice type, not just for Swift...and not even just for LVK GWs!
![image](https://user-images.githubusercontent.com/20259411/185798156-68d3c602-dd7e-4ee2-9744-9d85fbed0a49.png)

See documentation here: https://gcn.gsfc.nasa.gov/counterpart_tbl.html

@eburnsastro @lpsinger

**Comment by Tohuvavohu** [comment]
This needs to reopen! Counterpart notices are not even GW specific!
read the docs: https://gcn.gsfc.nasa.gov/counterpart_tbl.html

**Comment by lpsinger** [comment]
Are we sure that these are all that general? This is what the text looks like:

```
TITLE:          GCN/GRB_COUNTERPART POSITION NOTICE
NOTICE_DATE:    Sun 31 Jul 22 02:51:19 UT
NOTICE_TYPE:    Other
TRIGGER_NUM:    1118357
CNTRPART_RA:    225.0142d {+15h 00m 03.4s} (J2000),
                225.5429d {+15h 02m 10.2s} (current),
                223.8553d {+14h 55m 25.2s} (1950)
CNTRPART_DEC:   -69.4959d {-69d 29' 45.2"} (J2000),
                -69.5843d {-69d 35' 03.6"} (current),
                -69.2971d {-69d 17' 49.5"} (1950)
CNTRPART_ERROR: 6.5 [arcsec, radius]
GRB_DATE:       19790 TJD;   211 DOY;   22/07/30
GRB_TIME:       57054.00 SOD {15:50:54.00} UT
OBS_DATE:       19790 TJD;   211 DOY;   22/07/30
OBS_TIME:       57054.0 SOD {15:50:54.00} UT
OBS_DUR:        3312.1 [sec]
INTENSITY:      1.60e-13 +/- 7.00e-14 [erg/cm2/sec]
ENERGY:         0.3-10 [keV]
TELESCOPE:      Swift-XRT
SUBMITTER:      Phil_Evans
SUN_POSTN:      130.33d {+08h 41m 19s}  +18.29d {+18d 17' 14"}
SUN_DIST:       108.92 [deg]   Sun_angle= -6.3 [hr] (East of Sun)
MOON_POSTN:     158.29d {+10h 33m 09s}  +14.32d {+14d 18' 58"}
MOON_DIST:       95.80 [deg]
MOON_ILLUM:     5 [%]
GAL_COORDS:     313.82, -9.39 [deg] galactic lon,lat of the counterpart
ECL_COORDS:     247.57,-49.54 [deg] ecliptic lon,lat of the counterpart
COMMENTS:       GRB COUNTERPART Coordinates.  
COMMENTS:       We cannot confirm whether this is the GRB or serendipitous.  
```

Notice the title "GRB_COUNTERPART POSITION NOTICE" and the comment, "We cannot confirm whether this is the GRB or serendipitous."

**Comment by Tohuvavohu** [comment]
Yes notice it says GRB and not GW!

**Comment by Tohuvavohu** [comment]
To be clear, the counterpart notice associates a new transient with an alert of (in principle) arbitrary type (either GW, or GRB, or..)

**Comment by lpsinger** [comment]
OK, what "tags" should we attach to this notice type on this page?

**Comment by Tohuvavohu** [comment]
All tags?

**Comment by lpsinger** [comment]
Given that it says "GRB" in many places, are these supposed to be counterparts _of GRBs_?

**Comment by Tohuvavohu** [comment]
Read the docs! They are counterparts OF GWs, OR OF GRBS (or OF ....) .
https://gcn.gsfc.nasa.gov/counterpart_tbl.html
It is (supposed to be) agnostic to the initial trigger to be associated with.

**Comment by lpsinger** [comment]
The notice type and topic name is `LVK_COUNTERPART`. Should we change that to `COUNTERPART`?

**Comment by lpsinger** [comment]
Note, see 4ca6924b6d1e0a856a961ab87cb87f078d425dfb.
