### ISSUE TITLE
Create baseline playwright tests for Circulars search results

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2350]
# Description
Related to #2288 

In order to evaluate the Lucene search implementation, it's beneficial to establish some common search queries to ensure the Lucene search implementation does not affect the quality of search in non-lucene cases. Search queries that should be evaluated include
(a) Search queries that provide acceptable results in the current search
(b) search queries that do not provide acceptable results in the current search
Testing the former will ensure the lucene style search system does not impact or reduce the quality of basic searches, while the latter will evaluate if the lucene style search system is able to handle queries not currently covered by the search implementation.

#2288 should _not_ block the tests, as the Playwright tests can evaluate the performance of the current multi_match search system as a baseline. It is more likely that #2288 is blocked by this.

# Acceptance criteria

- [ ] Establish which search queries to evaluate
- [ ] Document the "known good" results that should be shown for a given query that constitute acceptable search performance
- [ ] (tangential to above) determine what constitutes acceptable search performance. Should it be all "good" results? Or a certain weighted percentage?
- [ ] Implement Playwright tests for these search queries

**Comment by tylerbarna** [comment]
If someone could remove the enhancement label, I don't think that's accurate for this issue

**Comment by lpsinger** [comment]
Let's start to capture these as a Playwright test, please.
