### ISSUE TITLE
Migrate cloud formation template from developer to private GitHub repo

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2361]
# Description

Move CloudFormation templates from developer.nasa.gov to GitHub.com private repo.

# Acceptance criteria
- Move account-specific settings to SSM parameters.
- Update CloudFormation stack to get those parameters from SSM.
- Create new private GitHub repo, and transfer contents of old repo WITHOUT preserving git history.
- Archive old developer.nasa.gov repo, and close developer.nasa.gov NAMS access for everyone that we are paying for.

**Comment by lpsinger** [comment]
Done: https://github.com/nasa-gcn/gcn-infrastructure
