### ISSUE TITLE
Edit Circular form does not populate date and time fields

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#2368]
Please add some Playwright tests for Circulars submission, moderation, and editing workflows. We have a lot of broken corner cases.

# Current behavior

The date and time fields are blank.

![Screenshot 2024-06-13 at 19 54 41](https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/6cb14f01-02f6-4afd-a8a1-e0798edd321e)

# Expected behavior

Fields should be populated

# Steps to reproduce

Navigate to https://dev.gcn.nasa.gov/circulars/edit/33671

# Environment

Safari, macOS

**Comment by dakota002** [comment]
That is a weird one, it populates correctly if you click the link to Request a Correction but not just straight to the link
