### ISSUE TITLE
Submitting Circular correction causes loss of seconds precision on submission time

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#2388]
# Current behavior

When you request a correction, it appears that the submission time is truncated to the nearest minute.

# Expected behavior

Seconds precision should be preserved, and time picker should show seconds precision.

# Steps to reproduce

![Screenshot 2024-06-21 at 09 53 23](https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/cc5928bd-7f4c-4fd8-a41c-2abaf4e2fc37)

# Environment

Unknown

**Comment by Courey** [comment]
@lpsinger  I let you know that the current time picker did not support seconds granularity. You wanted me to use the HTML input with type time instead. I have run into some issues with this approach.

In the image below you will see in the terminal that the values in default time and the time hook are both correct. They account for seconds and are in the requested 24 hour format. Unfortunately the browser detects your system settings and if you are using 12 hour time on your computer, the browser will convert times from 24 hour to 12 hour and add the AM/PM selector.

<img width="1093" alt="input_type_time_issue" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/e5c5a8c6-9379-4982-8642-7fbc7f0fe4d8">

It also does not seem to handle seconds granularity well. While I can get the seconds to display properly, if you hover over the input, you can see an error message that indicates seconds are not valid and prevents submission.

<img width="580" alt="Screenshot 2024-06-27 at 2 03 41 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/05e6f645-87ad-4411-a177-6c3e1da91faa">

I believe we will have to use a package or custom input to handle both seconds and 24 hour time. A custom approach is inadvisable.

Would using react time picker be an adequate solution? [Here is the github repo](https://github.com/wojtekmaj/react-time-picker). [Here is the NPM page](https://www.npmjs.com/package/react-time-picker). I have not tried it yet (or any other packages for that matter). I figured I'd check in and see if you have any strong preferences first.

**Comment by lpsinger** [comment]
Let's start with just the native `<input type="time">` because that will at least fix the bug. Let's get that merged first. Then maybe we can try out the third-party component.

**Comment by Courey** [comment]
This **was** the native `<input type="time">`

**Comment by lpsinger** [comment]
Yes, I know. The current implementation already has the problem that it uses the locale rather than 24-hour time. I don't understand the validation error, but I'm sure we can fix that. Would you please make a draft PR? I can help you with it.

**Comment by Courey** [comment]
Ah, are saying forget about the 24 hour part and just do the seconds and we can handle the 24 hour format later?

**Comment by lpsinger** [comment]
> Ah, are saying forget about the 24 hour part and just do the seconds and we can handle the 24 hour format later?

Yes.
