### ISSUE TITLE
Broken GCN Notice URLs

### ISSUE THREAD

**Issue by robertdstein** [nasa-gcn/gcn.nasa.gov#2447]
# Current behavior

I'm not sure when this became an issue, but the URL links to GCN notices no longer work. For example, from the latest neutrino GCN Circular (https://gcn.nasa.gov/circulars/36195), the linked notice (https://gcn.gsfc.nasa.gov/notices_amon_g_b/139303_27647445.amon) no longer loads.

More broadly, the GCN notice tables linked on the main GCN Notice page (https://gcn.nasa.gov/notices) all seem to be broken too. For example the IceCube page e.g https://gcn.gsfc.nasa.gov/amon_icecube_gold_bronze_events.html or LVK page https://gcn.gsfc.nasa.gov/lvc_events.html do not load either.

# Expected behavior

These should all work.

# Steps to reproduce

Click on URLs

# Environment

Mac M1, OS Sonoma 14.3.1, Browser: Firefox 127.0.2. I confirm I get the same issue using Chrome instead.

**Comment by dakota002** [comment]
Hey @robertdstein, I am not noticing these errors when I click those links, are you still seeing them? The pages are loading consistently for me

**Comment by dakota002** [comment]
Closing this, likely just a temporary network issue and we haven't been able to reproduce it

**Comment by robertdstein** [comment]
Hi @dakota002 I was on vacation and am just catching up with this. 

I have investigated this more thoroughly and realised this is actually apparently a local issue for my institute's network. Accessing these pages from any other network is fine. Thanks for investigating, and apologies for the confusion! Sorry!

**Comment by dakota002** [comment]
No worries, happy to help!
