### ISSUE TITLE
Incorrect BAT trigger number in Bat light curve notices for GRB 240805A

### ISSUE THREAD

**Issue by DrPhilEvans** [nasa-gcn/gcn.nasa.gov#2507]
For GRB 240805A = Swift-BAT trigger 1246907; the `GCN/SWIFT_BAT_LIGHTCURVE` emails from the old GCN classic system all contained the wrong information in the email body.  The fields (trigger no, date, position etc) were all from the previous BAT GRB trigger (GRB240730A = trigger 1245636). The email attachments, however, were correct, as was the BAT position and scaled map notice (and the XRT notices).

# Current behavior
Email body for BAT lightcurves contained previous triggers' details.

# Expected behavior
Email body for BAT lightcurves should contain current triggers' details.

# Steps to reproduce
N/A
# Environment
N/A

**Comment by jracusin** [comment]
After consultation with Teresa, she confirmed that there was an issue with information being stored in a buffer that needed to be cleared out.  That was done shortly after this issue and had resolved it.
