### ISSUE TITLE
Add optional email/kafka distribution for Circular revisions

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#2562]
# Description

When authors request a major change to a Circular (e.g. trigger time or magnitudes/flux change), give moderator option to distribute new version via email/Kafka.

# Acceptance criteria

- add Circular JSON schema revision number as field
- Moderator button to optionally distribute new Circular version over email and Kafka
- Add reminder to moderators of what constitutes a major change
- update documentation to say that we may distribute a new version if there's a significant data change

**Comment by lpsinger** [comment]
The Kafka part of this is dead simple: I think that we should _always_ send revised Circulars over Kafka. https://github.com/nasa-gcn/gcn.nasa.gov/pull/2568

**Comment by dakota002** [comment]
@lpsinger and @jracusin can you revise the acceptance criteria for this ticket? If we are going to always send the revised circular, what changes are left to make?

**Comment by lpsinger** [comment]
Are we? I think it is clear that we should always send the Kafka record. I am less sure if we always want to send the email.

**Comment by dakota002** [comment]
Ah I see, I thought by your update we were just going to always send the messages either way. All good then

**Comment by dakota002** [comment]
@jracusin @lpsinger for the reminder to the mods, is something like this what y'all have in mind
![image](https://github.com/user-attachments/assets/bc00da1c-f4d9-4a45-819a-727e010a0657)

**Comment by lpsinger** [comment]
> @jracusin @lpsinger for the reminder to the mods, is something like this what y'all have in mind?

No. If there is a checkbox, then the documentation about it should be in the label for the checkbox, not at the top of the page.

**Comment by dakota002** [comment]
Gotcha, as for the changes themselves, what are they?

**Comment by lpsinger** [comment]
None as far as I can tell. Just that detailed instructions related to a field in a form should usually go in or near the label for the control itself. Here's an example:

![Screenshot 2024-09-06 at 15 13 01](https://github.com/user-attachments/assets/ad842085-8dac-4e83-8cad-9378cd76d1c0)
