### ISSUE TITLE
Standardize .vscode settings

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#2596]
# Description
Either add `.vscode` to `.gitignore` or version it so all developers use similar/the same settings, such as formatting on save

# Acceptance criteria

- [ ] .vscode file settings are versioned and standardized

**Comment by tylerbarna** [comment]
As suggested by @dakota002

**Comment by dakota002** [comment]
@tylerbarna Do you remember which settings were conflicting in your local?
