### ISSUE TITLE
blocked ips???

### ISSUE THREAD

**Issue by cosmicbrucee** [nasa-gcn/gcn.nasa.gov#2671]
# Current behavior
GCN will not permit login; will not permit password resets; will give error when requesting help as well! The only thing that is different from previous successful logins is migration to newer system since 2024 Oct (possilby my last login) and that I'm logging in from Nazarbayev University, Kazakhstan

I note that my browser attempts to use the UID from some other NASA site, a UID not an email address. I overrode this. 

# Expected behavior

# Steps to reproduce
login from Nazarbayev University, Kazakhstan, as me

# Environment
macOS 12.7.6, Safari browser 17.6

**Comment by lpsinger** [comment]
Hi @cosmicbrucee. GCN is not configured to block any IP addresses. Would you please send a screenshot of the error that you see in your browser.

**Comment by cosmicbrucee** [comment]
Hi Leo:  Thanks for answering. 

Here is what happens when I Try to log in: 



I believe that is incorrect, that I am a registered user at ***@***.*** because on Oct 18,2020 I received a "Dear Submitter" email to this email address. 

OK, after doing that several times, I click on "forgot password?" and I enter my email, and I get: 



OK, so now I try to contact support:  

I go back toward the home page, at the bottom of the page, it says "Contact GCN directly."  I click on this, go to https://gcn.nasa.gov/contact and fill out the form, but this time it works.   (Sorry for any trouble, I made the subject line, "Test for Leo Singer". 

So, your contact form seems to work now, but I still can't log in. I hope these messages are helpful. 


-Bruce




> On Nov 5, 2024, at 4:26 PM, Leo Singer ***@***.***> wrote:
> 
> 
> Hi @cosmicbrucee. GCN is not configured to block any IP addresses. Would you please send a screenshot of the error that you see in your browser.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

UC Berkeley Space Sciences Laboratory
***@***.***
voice- 510.735.8806
fax - please send scans by email

**Comment by lpsinger** [comment]
> Hi Leo: Thanks for answering. Here is what happens when I Try to log in: I believe that is incorrect, that I am a registered user at ***@***.*** because on Oct 18,2020 I received a "Dear Submitter" email to this email address.

I don't see a screen shot or an error message there. Did you forget to add an attachment?

**Comment by cosmicbrucee** [comment]
Hello: 

This has not been resolved.  I am back in the US now, and I tried to reset my password with the email address used to send me GCNs.  It says, "Could not reset password for the account, please contact support or try again". 

It sounds to me like there is an issue with migration from the old system to the new. However, I cannot issue GCNs any more until I find my password. 

-Bruce


> On Nov 12, 2024, at 7:06 AM, Judy Racusin ***@***.***> wrote:
> 
> 
> Closed #2671 as completed via a260643.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

UC Berkeley Space Sciences Laboratory
***@***.***

**Comment by lpsinger** [comment]
Hi @cosmicbrucee. I closed the GitHub issue because we added an FAQ about IP address restrictions: https://gcn.nasa.gov/docs/faq#does-gcn-block-ip-addresses-or-connections-from-certain-countries.

I also see that we are tracking a support thread about resetting your password. Support threads are different from GitHub issues. Please check your inbox for a message coming from support@gcn.nasa.gov and respond to that.
