### ISSUE TITLE
Ingest GCN Circular submissions via emails through Amazon SES

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#290]
* [x] How much will it cost?
* [x] What service quotas affect us, and do we need to request any quota increases?
* [x] How do we trigger an action on receipt of an email? What integrations with Amazon compute services are available? 
* [ ] We have weaker guarantees about a user's identity when they submit an email than we do when they submit a form. Determine what measures are reasonable and necessary to verify that an email comes from an authorized user.

**Comment by dakota002** [comment]
### Cost
https://aws.amazon.com/ses/pricing/

From the pricing page: 
Incoming mail chunks
An incoming mail chunk is 256 kilobytes (KB) of incoming data, including headers, message content (text and images), and attachments. When you use Amazon SES to receive email, you pay $0.09 for every 1,000 incoming mail chunks.

We only count complete incoming mail chunks. For example, if you receive 768KB of incoming email, we count it as three incoming mail chunks. If you receive 255KB of incoming email, we count it as zero incoming mail chunks.

@lpsinger @jracusin  How big are the circulars when submitted this way?

No immediate quotas are listed for this feature on that page, but I will keep looking.


### Actions

https://docs.aws.amazon.com/ses/latest/dg/receiving-email.html

and further in https://docs.aws.amazon.com/ses/latest/dg/receiving-email-concepts.html

From the first page:

"Receipt rules (recipient-based control) provide the finest granularity of control over incoming email. Receipt rules can do advanced processing such as deliver incoming mail to an Amazon S3 bucket, publish it to an Amazon SNS topic, send it to Amazon WorkMail, or automatically send bounce messages when messages are to specific email addresses, and more."

So it is could be possible to use receipt rules to pass the body content to a service that we have running that could parse the content into a new Circular, then convert it to JSON, and then hand it off to a REST API service to save it. 

I'm open to other suggestions on the workflow of this part, but it seems like all of the pieces exist for us to bridge this gap

**Comment by dakota002** [comment]
@lpsinger what are your thoughts on this flow for the ingestion of circulars?

```mermaid
flowchart TD
subgraph RemixAPILayer
	E(API hosted on the Remix site: \n https://gcn.nasa.gov/api/circulars) --> F(DB Solution Dynamo, RDS? )
	F --> G(Confirmation Email to user)
end
A(User Email) --> B(SES)
B -->|via SES actions| C(S3)
C -->|via SE Triggers| D(Ingestion Lambda)
D --> RemixAPILayer
```

## SES

Handles receipt of the incoming emails.  Add an S3 action to the receipt rules

## S3 Bucket

Store the incoming email for later review or something. Then fire off a trigger based on s3:ObjectCreated:Put passing the object to a lambda

### Required Permission Sets:

Replace **AWSDOC-EXAMPLE-BUCKET** with the name of the bucket. and  **111122223333** with AWS account ID. I assume this will be added or configured maybe through the yml though
```
{ 
	"Version": "2012-10-17", 
	"Statement": 
	[ 
		{ 
			"Sid": "AllowSESPuts", 
			"Effect": "Allow", 
			"Principal": { "Service": "ses.amazonaws.com" }, 
			"Action": "s3:PutObject", 
			"Resource": "arn:aws:s3:::AWSDOC-EXAMPLE-BUCKET/*", 
			"Condition": { 
				"StringEquals": { 
					"aws:Referer": "111122223333" 
				} 
			} 
		} 
	] 
}
```

## Ingestion Lambda

This could also be triggered from SES, however the lambda apparently does not include the message body unless we also specify an SNS action. [Here](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-lambda-event.html#receiving-email-action-lambda-event-snsaction) is a way to have this trigger instead, but if we use the S3 bucket from the start, we can probably not worry about this.

### Code Behavior

- Verify user through cognito
	- Lookup user based on email
		-  return a fail response if non existing user
	- If the user is in the submitter group, get users name, association, and client credentials from dynamo (OR we could add 2 new attributes to the table in cognito, a DisplayName and Association that the users would be able to set once approved as submitters, or before idk ) and cognito.  
		-  return fail response if not in group
-   Construct JSON to include:
	```
	{
		subject,
		body,
		userDisplayName,
		association,
		clientId,
		clientSecret
	}
	```

The form validation will sit at the api layer, to keep it in one place. Will be addressed with https://github.com/nasa-gcn/gcn.nasa.gov/issues/296

**Comment by lpsinger** [comment]
> This could also be triggered from SES, however the lambda apparently does not include the message body unless we also specify an SNS action. [Here](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-lambda-event.html#receiving-email-action-lambda-event-snsaction) is a way to have this trigger instead, but if we use the S3 bucket from the start, we can probably not worry about this.

It's also possible to [deliver the entire email, body and all, to an SNS topic](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-sns.html) and then you can have a subscription to that SNS topic that fires a Lambda.

What are the pros and cons of this approach versus S3?

**Comment by lpsinger** [comment]
> Verify user through cognito

Remember that legacy users will _not_ have accounts in Cognito. We must have a (DynamoDB) table of allowed email addresses, some of which belong to Cognito users and some of which belong to legacy users. Authentication for email submission must only be based on the sender email address.

**Comment by lpsinger** [comment]
> clientId,
> clientSecret

Which client ID and client secret?

**Comment by lpsinger** [comment]
> > This could also be triggered from SES, however the lambda apparently does not include the message body unless we also specify an SNS action. [Here](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-lambda-event.html#receiving-email-action-lambda-event-snsaction) is a way to have this trigger instead, but if we use the S3 bucket from the start, we can probably not worry about this.
> 
> It's also possible to [deliver the entire email, body and all, to an SNS topic](https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-sns.html) and then you can have a subscription to that SNS topic that fires a Lambda.
> 
> What are the pros and cons of this approach versus S3?

After discussing this, I agree with going the SES -> S3 -> Lambda route.
