### ISSUE TITLE
Front-end design for GCN Circulars

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#293]
1. [x] Peer endorsement process: request an endorsement, approve an endorsement
2. [x] Email notifications: for users who want to get them in their inbox, but don't need to be able to submit them. Reuse the Email Notifications service?
3. [x] Submission: compose and submit Circulars through a form
4. [x] GCN Circulars archive: at least needs feature parity with https://gcn.gsfc.nasa.gov/gcn3_archive.html
5. [x] Moderation: delete (e.g. for offensive content), modify (e.g. for editorial corrections), associate with events (e.g. https://gcn.gsfc.nasa.gov/selected.html)

**Comment by dakota002** [comment]
This one is for some shared components: https://github.com/nasa-gcn/gcn.nasa.gov/pull/399

More UI updates will come after other PRs are approved

**Comment by Vidushi-GitHub** [comment]
Regarding moderations, tasks to be completed are: 
- [ ] Cross-linking of GCNs and ATels.
- [ ] GCN modification: one of the suggestion is Erratum, but with same GCN number
