### ISSUE TITLE
GCN Circulars REST API

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#296]
Design and implement a REST API for submitting and receiving GCN Circulars. Probably can be part of the Remix web site and use resource routes.

**Comment by dakota002** [comment]
depends on https://github.com/nasa-gcn/gcn.nasa.gov/pull/367

**Comment by dakota002** [comment]
I have a branch that adds routes as /api/circulars

The loader function handles gets, action for post, but its largely just commented out code until the other PRs get in

**Comment by jracusin** [comment]
OpenID Connect for authentication, OIDC refresh tokens for programmatic access

**Comment by dakota002** [comment]
@lpsinger Is this still an open issue? Or does the `_gcn.api.circulars` route resolve it?

**Comment by lpsinger** [comment]
Yes, it does. Good catch!
