### ISSUE TITLE
Configuration information for Java Kafka clients missing

### ISSUE THREAD

**Issue by david-sitsky** [nasa-gcn/gcn.nasa.gov#358]
Hi - it would be great in your "Get Sample Code" section to have an example for Java clients as well.  Can you provide an example here as to what should be expected, particularly for the sasl.jaas.config setting?  Thanks.

**Comment by lpsinger** [comment]
Thanks! We'll get to this as soon as we can, although we are short on Java developers at the moment. Pull requests are welcome.
