### ISSUE TITLE
update FAQ on email notices

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#373]
Need to update this FAQ now that this has been implemented.
[How do I receive GCN Notices via email from GCN Classic over Kafka?](https://gcn.nasa.gov/circulars#how-do-i-receive-gcn-notices-via-email-from-gcn-classic-over-kafka)

**Comment by Vidushi-GitHub** [comment]
This feature has been implemented now. Start streaming notices using [GCN classic over Kafka](https://gcn.nasa.gov/quickstart) and receive them via Kafka or email.

**Comment by jracusin** [comment]
Yes, but we need to update the web page.  https://gcn.nasa.gov/docs/faq
