### ISSUE TITLE
Group GCN Circulars by transient name

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#611]

**Comment by Courey** [comment]
What do you envision the groupings looking like? Will it just be the order they appear or will there be visual groupings?

**Comment by jracusin** [comment]
> What do you envision the groupings looking like? Will it just be the order they appear or will there be visual groupings?

In the GCN Classic archive (https://gcn.gsfc.nasa.gov/gcn3_archive.html), one could view by source type or individual event (https://gcn.gsfc.nasa.gov/selected.html), as in a particular GRB.  That's what we're trying to reproduce in the new system.  This has been a much requested feature.

**Comment by Courey** [comment]
Awesome, that is very helpful. thank you!

**Comment by dakota002** [comment]
Closing, replaced by https://github.com/nasa-gcn/gcn.nasa.gov/milestone/16
