### ISSUE TITLE
Distribute GCN Circulars by email

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#612]
We also need to work out how people opt in to receiving them.

- [x] Cognito users
- [x] Legacy users

**Comment by lpsinger** [comment]
NB: we must remember that legacy users may be signed up to just receive or just send Circulars and take that into account in the email-incoming lambda. See https://github.com/nasa-gcn/gcn.nasa.gov/pull/618#discussion_r1107763657.

**Comment by dakota002** [comment]
@lpsinger for legacy users who only receive, is there any information other than their email that we need? I think it might just be enough for that group to just put the receivers' emails into a dynamodb table and just get the whole list

**Comment by lpsinger** [comment]
No, I don't think so.

**Comment by dakota002** [comment]
For the Cognito Users: #689

**Comment by dakota002** [comment]
Legacy Users: #704
