### ISSUE TITLE
GCN Circulars bugs/suggestions

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#633]
For more information, see [docs](https://dev.gcn.nasa.gov/circulars) should point to https://dev.gcn.nasa.gov/docs/styleguide

**Comment by jracusin** [comment]
New - should be more obvious, perhaps "Submit New GCN Circular"

**Comment by jracusin** [comment]
Does a user who has not yet been peer endorsed see the "New" button?  Might need it to be grayed out, with a mouse over that says, "You must be peer endorsed to submit a new GCN Circular"

**Comment by jracusin** [comment]
In New GCN Circular compose, separate out boxes for authors from body.  That'll make it easier to separate out in a JSON file.

**Comment by jracusin** [comment]
We should also create a Kafka topic to serve circulars.

**Comment by lpsinger** [comment]
> New - should be more obvious, perhaps "Submit New GCN Circular"

That's rather verbose. Could that be a tooltip?

**Comment by lpsinger** [comment]
> In New GCN Circular compose, separate out boxes for authors from body. That'll make it easier to separate out in a JSON file.

This can be a "future enhancement".
