### ISSUE TITLE
Evaluate email authentication, spam, and virus scanning results for incoming GCN Circulars

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#638]
Amazon SES provides a number of authentication, spam, and virus evaluation results in message headers and in SNS notification records. Determine which of these evaluations are relevant and check their results in the email-incoming lamba.

See https://docs.aws.amazon.com/ses/latest/dg/receiving-email-concepts.html#receiving-email-auth-and-scan.

**Comment by jracusin** [comment]
GCN Classic also strips out plain text, and only includes that in distributed and archived circulars.  Is this something we want to do?

**Comment by lpsinger** [comment]
For now, yes.
