### ISSUE TITLE
Distribute Circulars via Kafka

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#686]
**Description**

There's community interest in receiving circulars via Kafka.  They're already stored in JSON objects, so we should setup a Kafka topic for them.

**Acceptance Criteria**
- add Kafka topic: gcn.circulars
- produce to gcn.circulars from circulars json files
- add circulars to Quickstart under JSON option
- announce it and add news item

**Comment by PeterBKramer** [comment]
It would be great if you could add two fields in the Kafka package extracted from the current email forms;  in addition to the mail.text add the mail.subject and the mail.date.  Thanks!

**Comment by lpsinger** [comment]
They're not quite ready yet. We haven't deployed this change yet.
