### ISSUE TITLE
Update submission no-reply email text body

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#710]
use this as an opportunity to remind people of the new system

- [x] Judy draft text
- [x] Dakota implement in code

**Comment by jracusin** [comment]
Here's some draft text, largely taken from the announcement circular draft.

Dear Submitter,

The email message you submitted to the GCN Circular service has been received and is being distributed to the GCN Circulars subscribers, and posted to the GCN Circulars archive (https://gcn.nasa.gov/circulars).  If you have selected to receive Circulars, then you will receive your copy shortly.

As of April 12, 2023, GCN Circulars are being administered through the new General Coordinates Network (GCN; https://gcn.nasa.gov), and no longer through the GCN Classic service (https://gcn.gsfc.nasa.gov).

The new GCN Circulars allow you to:
- Browse and search Circulars in our all-new archive.
- Sign yourself up or manage your own email subscriptions.
- Enroll yourself and your colleagues to submit Circulars with arXiv-style peer endorsements for new contributors.
- Submit Circulars with our new Web form, or continue to submit by email.

If you have not already done so, we encourage you to make an account at https://gcn.nasa.gov.  Even if you have not yet created a new account, these features provide continuity with the legacy GCN Classic service:
- Your Circulars settings have been transferred automatically.
- You are able to submit Circulars from the same email addresses registered in the legacy service.
- Emails from GCN come from a new address, no-reply@gcn.nasa.gov.
- We encourage you to submit Circulars to the new address, circulars@gcn.nasa.gov, but we still support the old address gcncirc@capella2.gsfc.nasa.gov.
- The new archive, https://gcn.nasa.gov/circulars, includes all past Circulars. We have frozen the old archive,
  https://gcn.gsfc.nasa.gov/gcn3_archive.html.

For more information about the GCN Circulars, please see https://gcn.nasa.gov/circulars.

For questions, issues, or bug reports, please contact the GCN Team via:

- HEASARC feedback form:
  https://heasarc.gsfc.nasa.gov/cgi-bin/Feedback?selected=kafkagcn

- GitHub issue tracker:
  https://github.com/nasa-gcn/gcn.nasa.gov/issues

**Comment by dakota002** [comment]
There are some replies for failures in [/app/events/email-incoming/index.ts](https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/events/email-incoming/index.ts) if you want to expand on those a bit too. They cover invalid body/subjects and missing permissions

**Comment by dakota002** [comment]
Here is the start of this for the Successful submit: #717

**Comment by jracusin** [comment]
In [/app/events/email-incoming/index.ts](https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/events/email-incoming/index.ts):
        subject: 'GCN Circular Submission Warning: Missing permissions',
        body: 'You do not have the required permissions to submit GCN Circulars. If you believe this to be a mistake, please fill out the form at https://heasarc.gsfc.nasa.gov/cgi-bin/Feedback?selected=kafkagcn, and we will look into resolving it as soon as possible.',

change to 
        subject: 'GCN Circular Submission Warning: Not an Authorized Submitter',
        body: 'The email address you are submitting this circular from is either not a approved legacy submitter or you have not completed the peer endorsement process, which authorizes you to submit GCN Circulars. If you believe this to be a mistake, please fill out the form at https://heasarc.gsfc.nasa.gov/cgi-bin/Feedback?selected=kafkagcn, and we will look into resolving it as soon as possible.',

will also need to link to new documentation page in #721

**Comment by lpsinger** [comment]
@jracusin, is this issue complete now?
