### ISSUE TITLE
Move Swift.BAT.GUANO topic into kafka public consumer scope

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn.nasa.gov#724]
Right now swift.bat.guano is in a group that does not have a public scope.
Please move it to one that does have a public scope, so that people can listen!
@lpsinger @jracusin @dakota002

**Comment by dakota002** [comment]
@lpsinger which scope should the Producer and Consumers be generating credentials through? I set up a consumer with the kafka-public-consumer scope (on prod) and was not able to receive the alerts

**Comment by lpsinger** [comment]
I see the permission issue. I am fixing it now.

**Comment by lpsinger** [comment]
Try again now.

**Comment by dakota002** [comment]
I ran the listener and included:
```
config={
    auto.offset.reset':'earliest'
}
```
and got all the alerts, looks good!

**Comment by Tohuvavohu** [comment]
Thank you Leo!

**Comment by Tohuvavohu** [comment]
Hi,
I tried today to listen as Dakota was, and get this reply:
"b'Fetch from broker 2 failed: Broker: Topic authorization failed'"

![image](https://user-images.githubusercontent.com/20259411/230659043-8a485c74-2248-4f39-9975-85c72a5a3caf.png)

**Comment by lpsinger** [comment]
What is the scope of the credential that you are using?

**Comment by Tohuvavohu** [comment]
I'm was using the same credentials I did for production, i assumed since the topic has public consumer scope any credentials should work?

**Comment by lpsinger** [comment]
The permissions for the topic `swift.bat.guano` and topics starting with `swift.bat.guano.` are configured as follows:

- On dev.gcn.nasa.gov and test.gcn.nasa.gov: writable by `gcn.nasa.gov/kafka-guano-producer`, readable by `gcn.nasa.gov/kafka-guano-consumer`
- On gcn.nasa.gov: writable by `gcn.nasa.gov/kafka-guano-producer`, readable by `gcn.nasa.gov/kafka-guano-consumer` and `gcn.nasa.gov/kafka-public-consumer`

Note that when you create credentials using the web site https://gcn.nasa.gov, they _only_ work with the Kafka broker for gcn.nasa.gov. When you create credentials using the web site https://test.gcn.nasa.gov, they _only_ work with the Kafka broker for test.gcn.nasa.gov.

Are you trying to use production credentials to talk to the test Kafka broker or vice-versa?

**Comment by Tohuvavohu** [comment]
No, i am only using credentials defined on the production Kafka broker (gcn.nasa.gov).
I see the problem was that I assumed that the kafka-public-consumer scope applied to *all* credentials, even my kafka-guano-producer. I see now that I have to use different credentials to listen as I did to produce.
Thanks very much for the clarity here :)

I will note that is quite difficult (imposible?) for the user to tell what specific scope already created credentials have, see https://github.com/nasa-gcn/gcn.nasa.gov/issues/760
