### ISSUE TITLE
Fill in subject, date, and submitter for GCN Circulars -4 through 30

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#752]
The present-day metadata fields (SUBJECT, DATE, and FROM) were introduced in GCN Circular 31. GCN Circulars -4 through 30 did not have them. However, our database requires them.

I am filling in sensible placeholder values for these, but we should do the research to populate those fields correctly for these early Circulars.

**Comment by jracusin** [comment]
The current archive on dev.gcn.nasa.gov only goes as far back as GCN 424.  Where do these records exist?

**Comment by lpsinger** [comment]
They are in the tar archive at https://gcn.gsfc.nasa.gov/gcn3/all_gcn_circulars.tar.gz.

**Comment by Tohuvavohu** [comment]
Also here, easier to access: https://gcn.gsfc.nasa.gov/gcn3_arch_old1.html

**Comment by jracusin** [comment]
Once @dakota002 moderator system is in place, @Vidushi-GitHub & @jracusin will do detective work, reconstruct these and make them v2 without distribution.

Where don't have info (like date of submission), we'll make our best guess based on what's in the circulars and add a note to the bottom that says something like "[Moderator Note: This Circular predates the current format, so the information has been reconstructed from historical archives.  See previous version for original content.]"

**Comment by Vidushi-GitHub** [comment]
Here is the list of the GCNs info: https://drive.google.com/file/d/1OzVLWUZmC9ifxPUJo70Wv_qIvzAz4RE8/view?usp=sharing

**Comment by tylerbarna** [comment]
I went through the document of the subject, date, and submitter for circulars -4 through 30:

https://docs.google.com/document/d/1jcQMi6FnAzC_z_qJ56Nk6rgHwJY3xPFC_qWsm8gByWI/edit?usp=sharing
