### ISSUE TITLE
Rename GCN 18448a to 18448.5 and 18453a to 18453.5

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#753]
There were two GCN Circulars numbers that had collisions in assigning numbers: [GCN 18448](https://gcn.gsfc.nasa.gov/gcn3/18448.gcn3) and [GCN 18453](https://gcn.gsfc.nasa.gov/gcn3/18453.gcn3). The circulars with duplicate numbers were assigned the names [GCN 18448a](https://gcn.gsfc.nasa.gov/gcn3/18448a.gcn3) and [GCN 18453a](https://gcn.gsfc.nasa.gov/gcn3/18453a.gcn3). However, our new database requires the GCN Circular ID to be a number.

The fix that I am using in the migration script is to assign the duplicates half-integer IDs 18448.5 and 18453.5. We need to remember to add a note to both of these circulars to state that we renamed them.

**Comment by jracusin** [comment]
Once @dakota002 moderator tool is in place, we will make a v2 with this info explaining why it's called .5

**Comment by Vidushi-GitHub** [comment]
@jracusin I have initiated moderation with this PR. Please check if request is received to you.

**Comment by jracusin** [comment]
Note added to circulars in archive using moderation.
