### ISSUE TITLE
Circulars transitions not featured prominently enough on webpage

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#754]
Text about transition is smaller than details if webinar. The transition is more important than the webinars. Nothing on landing page says anything about circulars. Once announcement goes out, need obvious place to learn more.

**Comment by lpsinger** [comment]
The [USWDS web site](https://designsystem.digital.gov) has a hero with two buttons. We could try a similar design.

![Screenshot 2023-04-19 at 00 44 45](https://user-images.githubusercontent.com/728407/232969233-7f8a766d-787a-478b-afdc-f09dec74164e.png)

Let's finish #831 and #372 first, as this will give us more horizontal space to work with.
