### ISSUE TITLE
Show credential scope to user for easier credentials management

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn.nasa.gov#760]
For credentials that have already been created by a user, and shown on https://gcn.nasa.gov/user/credentials
there is no clear way to determine what scope they have!

eg, when testing I had to create a whole new credential to ensure that an issue was/wasn't caused by improper scope.

**Comment by lpsinger** [comment]
@dakota002, would you please take this one?

**Comment by dakota002** [comment]
On it!
