### ISSUE TITLE
Ability for GCN Team to send Announcements and users opt in/out

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#773]
- announcements email list managed like circulars list
- toggle button to subscribe/unsubscribe
- admin & moderator roles for website
- user interface for admins and moderators to send announcements

**Comment by dakota002** [comment]
@lpsinger and @jracusin any thoughts on the content of the email that gets sent out as the announcement? I currently just have:

`A new update, "${title}", has been posted to the GCN News page.

View more at ${origin}/news`
