### ISSUE TITLE
Explain sign in vs. sign up for legacy users

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#817]
This has tripped several users up:

> You said that current users have been migrated - but how do we log in to make the changes just demonstrated? I don’t have a password and I clicked “forgot password” but haven’t received the reset email it says was sent.

**Comment by jracusin** [comment]
Should we add a FAQ or do you have a way of being clearer in the sign in/up steps?

**Comment by lpsinger** [comment]
We decided that we would simply create true Cognito accounts for all legacy users.

**Comment by lpsinger** [comment]
@dakota002, I'm having second thoughts about the plan to create Cognito accounts for all users. It would make for even more confusing situations if a legacy user chooses to sign in with a federated IdP.

Let's address this with a FAQ.
