### ISSUE TITLE
Incoming GCN Circulars are double spaced

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#818]
See, for example, https://gcn.nasa.gov/circulars/33648.

This might be an email parsing, Unicode, or text encoding issue.

**Comment by dakota002** [comment]
I'm not sure this is actually an issue, it may just be how the sender formatted their email. 
https://gcn.nasa.gov/circulars/33649 looks correct, as does https://gcn.nasa.gov/circulars/33651

For this, should we just implement some parsing that strips excess line breaks?

**Comment by jracusin** [comment]
I talked to Tyler Parsotan about this issue, as his was one that was double-spaced (https://gcn.nasa.gov/circulars/33645).  He said he always had this problem with GCN Classic, and it has clearly persisted.  He had no idea why.

**Comment by dakota002** [comment]
I'm curious if it has something to do with their mail client of choice. Like if they are adding extra new lines to make it look correct on whatever machine the emails are coming from

 We could try to add something that parses out the `\r\n\r\n` and just replaces them with single line breaks, but that might mess stuff up for anyone who is intentionally doing it.

**Comment by lpsinger** [comment]
What kinds of newlines are in Tyler's message? Could this be Windows vs. Linux/UNIX/macOS style newlines (i.e. `\r\n` vs `\n`)?

**Comment by lpsinger** [comment]
> For this, should we just implement some parsing that strips excess line breaks?

Seems like that could easily have false positives.

**Comment by lpsinger** [comment]
I learned two things.

1. This isn't a Windows vs Linux/UNIX/macOS newline style issue because the RFCs that define email stipulate that emails use CRLF for line breaks (`\r\n`).
2. I took a look at Tyler's incoming emails and they really do have doubled newlines: I see `\r\n\r\n` everywhere.

@jracusin, would you please ask Tyler to describe the exact procedure that he uses to compose and send emails to GCN? Does he write them in Notepad and then paste them into Outlook, or what? If we could figure out what causes this, then we can at least write an FAQ about it.

**Comment by jracusin** [comment]
Tyler said that he uses Outlook, but he is manually adding line breaks, as GCN classic required.  He has another BAT refined analysis to send soon, and he said he'd try it without manual line breaks. So I'll keep an eye out to see if that's the issue.

**Comment by lpsinger** [comment]
Outlook on what operating system? How is he adding line breaks? Is he doing all of the editing in the Outlook compose window?

**Comment by parsotat** [comment]
I've got outlook on MacOS. I typically copy a template into a new email and edit the relevant portions (where the template does have the manual line breaks that were required for GCN classic). In the next GCN that I send out, I am going to try to remove the artificial line breaks and just have normal paragraphs.

here is an example of the template that is used: https://swift.gsfc.nasa.gov/results/BATbursts/1164980/bascript/bat_gcn_circular.txt

**Comment by parsotat** [comment]
I just sent a circular to the new email address (in the above gcn of mine that Judy referenced, I had used the old email address) and made sure to remove any artificial line breaks and the formatting looks like it is fixed now. 

<img width="1423" alt="Screenshot 2023-04-21 at 10 58 15 AM" src="https://user-images.githubusercontent.com/25468716/233669543-5442e6c7-bf27-4c4c-a872-aa550548bc85.png">

**Comment by lpsinger** [comment]
@parsotat, the next time that you and I are both in the office, I would like to watch exactly what you did differently. I am concerned that there may still be some issue where there is a specific email client configuration that results in duplicated newlines.

@jracusin, the style guide does not explicitly mention line wrapping, although it has been a common practice for a long time. If we are advising users _against_ line wrapping, then we should update the style guide accordingly.

**Comment by jracusin** [comment]
I will add back in something to the style guide about not putting in line breaks, and also a FAQ.

**Comment by lpsinger** [comment]
@parsotat, I was able to reproduce your issue by composing a message in Outlook with Format Text set to HTML and inserting the line breaks in the Outlook message editor.

The workaround seems to be to make sure that you are composing your message in plain text. #862 will add a FAQ entry about this.
