### ISSUE TITLE
Legacy users who already had accounts lost name/affiliation

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#839]
Can we manually add these back in?  These are frequent GCN Circular submitters, and there have been a bunch of circulars with email address only in the from field.

Alternatively, we could contact them and ask them to backfill, but it would probably be more effective if we just did it.

**Comment by dakota002** [comment]
@jracusin Can you explain a bit more on this? Did these individuals have cognito accounts prior to the new update? Are there specific users this happened for?

**Comment by jracusin** [comment]
Can we search for cognito users who do not have a name/affiliation in their profile, check if they were legacy users, and fill in that info?  Is there also any prompt for new users to set their profiles?

**Comment by dakota002** [comment]
Ah okay yes thats doable. I'll work on a script for that, but I think code wise it will end up in the migration repo

**Comment by dakota002** [comment]
The users names and affiliations should be correct now. Just need to do some dynamo cleanup

**Comment by jracusin** [comment]
Any chance of correcting the already processed circulars?

**Comment by dakota002** [comment]
Yep, that will take a little more work, but I think we can make that so

**Comment by dakota002** [comment]
@jracusin the circulars should now have the correct `FROM` data

**Comment by lpsinger** [comment]
Can we close this issue, then?
