### ISSUE TITLE
Require user to set profile before sending peer endorsement

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#847]
I got a peer endorsement request from a users with an ambiguous email address.  If they had their full name and affiliation set in the system and the request came with that it would be much easier to evaluate.  An optional ability to write a sentence explaining who they are would also help.

**Comment by lpsinger** [comment]
I am going to move this to "enhancements" because I want to close out all of the urgent and low-hanging issues from the webinar before we start doing new feature development again.
