### ISSUE TITLE
Circular form submission bug

### ISSUE THREAD

**Issue by Tohuvavohu** [nasa-gcn/gcn.nasa.gov#848]
I just submitted this circular: https://gcn.nasa.gov/circulars/33672 via the web form
and on pressing send it replied " An unexpected error has occured" 
but obviously submission seems to have been successful.

**Comment by lpsinger** [comment]
This was probably a transient issue. It often occurs when you have a browser window open while we are rolling out a deployment, so your browser is trying to fetch assets that we have replaced.
