### ISSUE TITLE
Mistake submissions in archive

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#868]
Add back in removed mistake submissions into archive with "Ops note".  See #859.

Acceptance Criteria:
- what would be useful would be a record to say why the circular was removed for being a mistaken submission.
- markdown page explaining discontinuity (this exists)

**Comment by jracusin** [comment]
Include something with a note about why they were removed.

**Comment by jracusin** [comment]
Example: 33045-33047 are all linked to [mistake60](https://gcn.gsfc.nasa.gov/gcn3/mistake60.txt), but they can still be found at https://gcn.gsfc.nasa.gov/gcn3/33045.gcn3

**Comment by jracusin** [comment]
See gcn3_archive.html and all of the gcn3_arch_old***.html files that link to gcn3/mistake*

**Comment by lpsinger** [comment]
https://gcn.nasa.gov/docs/circulars/archive#migration-of-archive-from-gcn-classic explains why these are missing from the archive.

**Comment by Courey** [comment]
closing as the page already exists explaining the discontinuity
