### ISSUE TITLE
Limit search by date range

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#878]

**Comment by lpsinger** [comment]
> Couple of clarifying questions:
> 
> * [ ]  I imagine we want this to be a modifier to a normal search so one can search for something like fermi circulars in a given date range?

Yes.

> * [ ]  For the date range, the date in question be the submission date, right?

Yes.

> * [ ]  Is there a specific syntax for a date range query that would work best, maybe something similar to ADS? Similarly, should it be able to handle European style dates as well (ie MM-DD-YYYY and DD-MM-YYYY)?

Definitely ISO 8601, possibly human date ranges too (like "10 days ago"). Also we definitely will want some kind of date and time picker widget.

> * [ ]  Do we want "open" queries (ie should there be an option to search for all circulars prior to or after a given date)?

Yes.

> * [ ]  Also, should there be a shorthand for getting circulars in a given day/month/year (so searching something like year:2022 would return all circulars from 2022 and searching month:05-2023 would return all circulars from May 2023)?

I'm not sure.

Note that `year:2022` looks a lot like [Lucene query syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) which is under the hood and supported by OpenSearch.

**Comment by lpsinger** [comment]
> For (1), I was looking into the [opensearch docs](https://opensearch.org/docs/2.0/opensearch/supported-field-types/range/) regarding the range field, which has a type specific to dates. This seemed like a potential solution, but I was having some trouble incorporating it with the multi_search in the search function, and I'm not sure if it can handle the native createdOn format easily.

We may not have defined the fields as the correct type in the [index mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/explicit-mapping.html). You can experiment with that in your local ElasticSearch instance that starts when you run `npm run dev`.

**Comment by tylerbarna** [comment]
@lpsinger do you think a date picker might be easier to implement? https://www.npmjs.com/package/react-datepicker

I was thinking it might be better to have some type of expandable component that contains "advanced" search inputs. For this issue, there can be a date picker, and issue #816 could also be fixed by adding some type of selection for object type; there could also be one to filter by mission 

I'd just need to figure out how to implement an expandable element

**Comment by lpsinger** [comment]
On second thought, times are not a requirement.

**Comment by tylerbarna** [comment]
> I encourage you to find and reuse an existing picker, but I think we want something that can do dates _and times_.

Oh, react-uswds already has something like this built in https://trussworks.github.io/react-uswds/?path=/story/components-date-range-picker--with-default-values

**Comment by tylerbarna** [comment]
So I was able to add date range picker elements, but I think I'll need to pull them out into a separate function from the default, and I also need to figure out how to properly store and retrieve the date variables so I can have a function that goes in and filters out any results that don't fall within the date range
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/c2db7244-43ca-477c-b3e3-a1836ca6fdbd)

My thought for the '>>' button was to have an accordion menu that expands out and shows the date range picker; I've been trying to figure this out, but I'm realizing it would probably be better to get the actual date range implementation working before trying to add the advanced search menu

**Comment by tylerbarna** [comment]
@lpsinger just to clarify, for the results returned by search, is it structured so each page of items is its own list? I'm having results print in the console for debugging, and I'm finding that it's printing out 3 times

**Comment by lpsinger** [comment]
> @lpsinger just to clarify, for the results returned by search, is it structured so each page of items is its own list? I'm having results print in the console for debugging, and I'm finding that it's printing out 3 times

I wouldn't be too worried if it's logging results multiple times. The code probably runs once on the server side and once on the client side.

**Comment by lpsinger** [comment]
> My thought for the '>>' button was to have an accordion menu that expands out and shows the date range picker; I've been trying to figure this out, but I'm realizing it would probably be better to get the actual date range implementation working before trying to add the advanced search menu

Yeah, I agree. Get the logic working and then tweak the UX. Some options for the UX:
- A "show advanced search options" checkbox or disclosure button, similar to your accordion concept
- A popover or dropdown for date filtering

For inspiration, take a look at other applications that have date filtering.

**Comment by tylerbarna** [comment]
> > @lpsinger just to clarify, for the results returned by search, is it structured so each page of items is its own list? I'm having results print in the console for debugging, and I'm finding that it's printing out 3 times
> 
> I wouldn't be too worried if it's logging results multiple times. The code probably runs once on the server side and once on the client side.

actually, looking closer, each results object that's printed by the console log seems to contain different objects, which I think are the items in each page, though I'll need to look a bit further into how the individual results objects are then loaded in. If I were to just drop in a function that goes through a results object and filters out circulars that have createdOn dates outside the accepted range, that wouldn't necessarily break anything, but it might cause the pages to have a different number of results. I think this has something to do with the Pagination function, but I haven't looked at it too closely

**Comment by lpsinger** [comment]
Yeah, that would break the pagination counts. I think we need to figure out how to have OpenSearch itself do the date filtering. Like I said, you probably need to adjust the OpenSearch type mapping so that it knows that the field that it has indexed is a date.

I might even suggest two PRs: one that adds the OpenSearch functionality to the backend and the loader function, and a second and later PR that adds the UI support.

**Comment by tylerbarna** [comment]
> Yeah, that would break the pagination counts. I think we need to figure out how to have OpenSearch itself do the date filtering. Like I said, you probably need to adjust the OpenSearch type mapping so that it knows that the field that it has indexed is a date.
> 
> I might even suggest two PRs: one that adds the OpenSearch functionality to the backend and the loader function, and a second and later PR that adds the UI support.

for the backend opensearch functionality, would that be the search function in circulars.server.ts or would that be implemented elsewhere?

**Comment by lpsinger** [comment]
> for the backend opensearch functionality, would that be the search function in circulars.server.ts or would that be implemented elsewhere?

Yes, the `search` function in `circulars.server.ts`. However to adjust the index type mapping you will need to first configure the index using an explicit type mapping (see https://opensearch.org/docs/latest/field-types/index/#explicit-mapping).

**Comment by tylerbarna** [comment]
So, with the changes I do in [this branch](https://github.com/tylerbarna/gcn.nasa.gov/tree/circulars-search-backend), I believe I've gotten something for the backend kind of working, the issue I'm having now is that I can search the original format of the createdOn property (for circular 1, '1672326096000') and get the expected circular, but trying to search something in an actual date format (for circular 1, '2022-12-29'), returns an error. The advancedQuery argument isn't being passed yet, so this is more likely an issue with the multi_match part

**Comment by tylerbarna** [comment]
> So, with the changes I do in [this branch](https://github.com/tylerbarna/gcn.nasa.gov/tree/circulars-search-backend), I believe I've gotten something for the backend kind of working, the issue I'm having now is that I can search the original format of the createdOn property (for circular 1, '1672326096000') and get the expected circular, but trying to search something in an actual date format (for circular 1, '2022-12-29'), returns an error. The advancedQuery argument isn't being passed yet, so this is more likely an issue with the multi_match part

okay, removing createdOn from the multi_match fields corrects this issue. I also think it'll probably be better to accept the dates from the date picker and then convert them to ms since the epoch and use those converted values in the search function so we don't have to change anything with the createdOn property.

**Comment by tylerbarna** [comment]
may also have to add some items to the url to specify the start and end dates

**Comment by tylerbarna** [comment]
[This commit](https://github.com/tylerbarna/gcn.nasa.gov/commit/279a19cc5153c84ef1de346641ab56b933477a1b) should have the backend for search implemented, but there's no frontend for selecting a date range right now. The date range can be checked by adding the startDate and endDate parameters inside the new advancedQuery parameter in the call to search when defining results in the loader. The values, when not provided, default to 0 and Infinity so all circulars are included. In terms of backend stuff, we might benefit from adding the advancedQuery to the URL so items can be retained like the query is, but that will require changes in circulars.server, index, and circularID, and I'm not sure if we should do it before or after implementing a frontend. Should I PR the backend commit to this issue or should I wait until the frontend stuff is figured out?

**Comment by lpsinger** [comment]
Let's have an initial PR that implements the backend, add support for the URL search params, and properly saves and restores the search params when navigating between pages and individual results.

The UI will be in a second PR.

**Comment by tylerbarna** [comment]
Working on applying the search params, but some change I made seems to be causing an issue with the URLSearchParams in the loader; after searching, I found that the parameters besides query were no longer included, but in the client side log, some of the logs I've added to getPageLink and Pagination do contain the other parameters. Changes can be seen [here](https://github.com/tylerbarna/gcn.nasa.gov/commit/17515315b04a1717220d41e79967aaa1fa5e9929#diff-a1c5ea089c9e2aa76355aab7711d6e416105bc19311e000004e2107d065f6e8a)

**Comment by tylerbarna** [comment]
> Working on applying the search params, but some change I made seems to be causing an issue with the URLSearchParams in the loader; after searching, I found that the parameters besides query were no longer included, but in the client side log, some of the logs I've added to getPageLink and Pagination do contain the other parameters. Changes can be seen [here](https://github.com/tylerbarna/gcn.nasa.gov/commit/17515315b04a1717220d41e79967aaa1fa5e9929#diff-a1c5ea089c9e2aa76355aab7711d6e416105bc19311e000004e2107d065f6e8a)

more specifically, when you first navigate to the circulars page, the loader seems to contain the necessary URL parameters, or at least it defines them correctly (the actual url on initial load contains no parameters, as we would expect):


```
loader url http://localhost:3333/circulars?page=1&startDate=-Infinity&endDate=Infinity
loader search params URLSearchParams { 'page' => '1', 'startDate' => '-Infinity', 'endDate' => 'Infinity' }
loader page 1

loader url http://localhost:3333/circulars?page=2&startDate=-Infinity&endDate=Infinity
loader search params URLSearchParams { 'page' => '2', 'startDate' => '-Infinity', 'endDate' => 'Infinity' }
loader page 2

loader url http://localhost:3333/circulars?page=3&startDate=-Infinity&endDate=Infinity
loader search params URLSearchParams { 'page' => '3', 'startDate' => '-Infinity', 'endDate' => 'Infinity' }
loader page 3
```

However, when interacting with page elements (searching, trying to go to page 2, etc), the loader seems to only have the query parameter, resulting in the results not being shown; I believe the lack of the page parameter is what's causing the page to be blank:

```
loader url http://localhost:3333/circulars?query=grb
loader search params URLSearchParams { 'query' => 'grb' }
loader page 1
```


That being said, the results are still being returned properly, as I can see them if I include a console log for the results, so I don't think it's an issue with the changes to the search function so much as issues with the changes to the functions in index.tsx
