### ISSUE TITLE
Add Schema documentation 

### ISSUE THREAD

**Issue by dakota002** [nasa-gcn/gcn.nasa.gov#921]
Acceptance Criteria 

Schema documentation pages exist for producers and consumers of notices:

- [x] Gitflow instructions for PRs and schema development
- [ ] Instructions on how to create multiresolution healpix maps
- [x] Instructions for constructing schema from Core Schema objects and additional instrument specific 
- [x] instructions on how to base64 encode fits files and include them in a JSON notice
- [x] Instructions for decoding base64 encoded fits file string (w/ example)
- [x] Best practices for schema updates (ex. Deprecation of fields that are being updated or replaced,)
- [x] Details of allOf and anyOf; when and why to use them
- [x] "unevaluatedProperties": false, https://github.com/nasa-gcn/gcn-schema/issues/80
- [x] Code for both schema and example: Strong starting point and min confusion

**Comment by lpsinger** [comment]
> * [ ]  Instructions on how to create multiresolution healpix maps

See follow-up issue: #1493.

**Comment by Vidushi-GitHub** [comment]
Already an issue exists for it, see #1205, although needs re-base now.

**Comment by Vidushi-GitHub** [comment]
Thanks @lpsinger, for completion of final deployment. @jracusin this should be good for making announcement.
