### ISSUE TITLE
No swift/fermi circulars displayed for GRB101219B/GRB101219686

### ISSUE THREAD

**Issue by nuessle167** [nasa-gcn/gcn.nasa.gov#932]
Detected in both the Swift-BAT and Fermi-GBM catalogs, but there are no returned GCN circulars, notices, or anything when the burst is searched.

**Comment by jracusin** [comment]
Thanks Pi.  I think the issue here is that the search function doesn't like "GRB" or "GRB ".

**Comment by jracusin** [comment]
Replied via email.
