### ISSUE TITLE
"back" after a search returns to search output but not necessarily the previous page

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/gcn.nasa.gov#969]
The fix for Issue #923 now returns to the search output, but if one goes to an item past the second page, the back button will return to the first page of the search output

**Comment by lpsinger** [comment]
It seems to be working for me. Are you sure?

**Comment by tylerbarna** [comment]
@lpsinger you're right, seems to be functioning correctly, was probably just a random issue on my end
