### ISSUE TITLE
Add link to agency honor award

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#995]
The "NASA Honor Awards" item from #978 needs a hyperlink to a NASA press release or announcement.

**Comment by jracusin** [comment]
I've sent some inquires to get a link.

**Comment by lpsinger** [comment]
Sheesh, I don't know what the point of that page even is.

Here's a URL that at least gets us to that one award: https://science.gsfc.nasa.gov/sed/index.cfm?fuseAction=award.AwardsSearch&#apoint

**Comment by jracusin** [comment]
Yes, but at least we're on it now at all.  It didn't get populated with our team along with the other awardees from 600 since it was just the name of the team and not the individuals.  I got that corrected by contacting the webmaster.

**Comment by lpsinger** [comment]
That page is now a 404, but the its replacement appears to be at https://science.gsfc.nasa.gov/sci/awards. However I don't see _any_ Agency Honor Awards listed. Would you please inquire again about when that award will be posted?

**Comment by ben-pelletier** [comment]
@lpsinger 
We can implement this on science.gsfc.nasa.gov in a few ways.
1) A standalone page that would be just the specific award that displays only that awards info (https://science.gsfc.nasa.gov/sci/awards/12345)
2) Query params for search filters in the URL ((https://science.gsfc.nasa.gov/sci/awards?search=myaward
or both...

Let me know if either meets your expectations and we can add to the next release.

**Comment by lpsinger** [comment]
1 would be fine. 2 would be fine as well as long as the query supports a permalink to _exactly one_ award.

**Comment by ben-pelletier** [comment]
1 would be best bet to avoid link rot in general. Will add to next release for science. Looking at likely 2 weeks out from today.

**Comment by ben-pelletier** [comment]
"Share" menu has been added to the awards on science.gsfc.nasa.gov, will let you get a standalone link for any award.

**Comment by lpsinger** [comment]
@ben-pelletier, the cookie crumb bar on the result page says "Award Awards". Would you please fix that? See screenshot below.

<img width="1113" alt="Screenshot 2024-05-06 at 12 16 16" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/20f2f9b5-749e-465a-8f9a-9181ab01c91b">

Also, I can't find our 2023 Robert H. Goddard Award.

**Comment by ben-pelletier** [comment]
Done.
This award you screenshotted has recipients in the description. I can modify it so that 'recipients' shows recipients names alongside the team itself. This would enable personnel tooltips, CV links, and organization tags/links.

**Comment by lpsinger** [comment]
Sure, that makes sense.

Where is our 2023 Robert H. Goddard Award?

**Comment by ben-pelletier** [comment]
Looks like this is it: https://science.gsfc.nasa.gov/sci/awards/1057. The recipient teams are listed together on the one record. I'm not sure if this is standard for RHG Award or not. I will discuss that internally and see if we need to reorganize some of that data.
